### PR TITLE
Multicontainer

### LINKED ISSUE #30: Report status of the users container to dashboard
Is it running? did it exit?
We could also allow users to Stop the container (without running another one), probably using an env var to signal the container should be in a Stopped state.

### LINKED ISSUE #52: Add ability to customise docker/rce flags used while updating applications.
Env vars?

### LINKED ISSUE #63: Writing config.json should be atomic
We can do it by creating a differently named file and then using an atomic rename.

### LINKED ISSUE #115: Ensure purge doesn't destroy mounted partitions

### LINKED ISSUE #194: Provisioning may complete without writing to config.json
A device had config partition mounted as read only, provisioning completed probably trying to write to config.json, but it never was able to.

Supervisor should not assume provisioning is complete if uuid is not written to config.json, because it is essential for vpn to function.

Front logo [Front conversations](https://app.frontapp.com/open/L2luYm94ZXMvdG9waWNzLzIzMDIx)

### LINKED ISSUE #226: IP addresses sometimes not being updated in the UI
As described by the user:

> I was using the beta QEMU x86 64bit device with two devices.
> At some point I switched from QEMU user networking to a bridge device for both of them.
> Only one of them showed an updated IP in the web interface.
> So one was still showing some 10.x IP, and the other was showing 192.168.5.x (my local network).
> They were both running for a good 30 minutes and both had 192.168.5.x addresses, but only the one updated in the web interface.
> 
> I recall I booted the same device OS in two machines at some point which may have confused it?
> (I assume you need to re-download the device OS for each device so that it can be uniquely identified, and I failed to do this once)

(Moved from https://github.com/resin-io/resin-ui/issues/39)

### LINKED ISSUE #348: Moving applications while the update lock is set causes the old app not to be stopped
When a user executes a device move, the supervisor sees a state change in the API that tells it to start running the new app, and remove the old one. This will cause the supervisor to try to start the new app and remove the old one in parallell (as it is done within a [promise .map](https://github.com/resin-io/resin-supervisor/blob/master/src/application.coffee#L639)).

If the update lock on the old app is set, stopping it will fail, but starting the new one will succeed, so the old app will remain running alongside the new (aka "duplicated containers").

In older devices this will also trigger the bug fixed in #346 - so the error will not be sent to the device logs.

A workaround to avoid this issue is to set the lock override (`RESIN_SUPERVISOR_OVERRIDE_LOCK = 1`, i.e. setting the lock override in the device's Actions page) *before* moving to the new app, which will cause the app to be properly stopped while the new one is being started.

If a device falls into this state, a hotfix can be applied by hitting the Supervisor API's `/v1/update` endpoint with the force parameter, e.g. running this from the webterminal:

```
curl -X POST --data '{"force":true}' -H 'Content-Type: application/json' $RESIN_SUPERVISOR_ADDRESS/v1/update?apikey=$RESIN_SUPERVISOR_API_KEY
```

This will cause the supervisor to run an update cycle forcing all locks, which will allow it to stop the old app.

The proper fix will require a re-architecture of how app moves are handled, somehow allowing the transition to be more orderly executed, ideally also applying update strategies for the change. This might be a bit of a challenge as it involves changes to the core update cycle, and we need to consider how it may affect future multi-container implementations.

Front logo [Front conversations](https://app.frontapp.com/open/top_1wo1)

### LINKED ISSUE #358: The lock on the new app is already there when it's moved, but the override is not set on the new app
This is another edge case associated with users using lock files and moving devices between app.

Front logo [Front conversations](https://app.frontapp.com/open/top_wn9)

### LINKED ISSUE #388: Some warnings from the supervisor logs
```
[2017-02-06T11:59:23.332Z] Knex:warning - sqlite does not support inserting default values. Set the `useNullAsDefault` flag to hide this warning. (see docs http://knexjs.org/#Builder-insert).
Mon, 06 Feb 2017 11:59:27 GMT body-parser deprecated bodyParser: use individual json/urlencoded middlewares at usr/src/app/src/proxyvisor.js:45:14
Mon, 06 Feb 2017 11:59:27 GMT body-parser deprecated undefined extended: provide extended option at usr/src/app/node_modules/body-parser/index.js:105:29
```

### LINKED ISSUE #423: Multiple entries of the same dtparam in config.txt
Adding the `RESIN_HOST_CONFIG_dtparam = audio=off` results in multiple entries in the config.txt on 
**HOST OS VERSION**
Resin OS 2.0.0+rev3 (dev)
**SUPERVISOR VERSION**
4.1.1 
```
root@62bf4c3:/mnt/boot# cat config.txt | grep audio
## hdmi_ignore_edid_audio
##     Pretends all audio formats are unsupported by display. This means ALSA
##     1        Pretend all audio formats are unsupported
#hdmi_ignore_edid_audio=1
## hdmi_force_edid_audio
##     Pretends all audio formats are supported by display, allowing
##     1        Pretend all audio formats are supported
#hdmi_force_edid_audio=1
##     Don't dedicate a pll to PWM audio. This will reduce analogue audio
## audio
##     Enable the onboard ALSA audio
#dtparam=audio=off
dtparam=audio=off
dtparam=audio=off
dtparam=audio=off
```

I think in some cases this cause problems if trying to set back to `audio=on` because the very last entry will override all the others.

Front logo [Front conversations](https://app.frontapp.com/open/top_1ya1)

### LINKED ISSUE #426: Deleting a config.txt variable should reset it to its default value
Where "default" means the value it had before the supervisor started running for the first time.

### LINKED ISSUE #439: supervisor listens on port 80 by default
Since we're using 48484 everywhere we should make this the default port of no one is supplied. cc @shaunmulligan

### LINKED ISSUE #450: Deleting a config.txt variable doesn't delete it from the file
Logs show:
```
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]: [2017-06-09T21:40:35.283Z] Will not set boot config:  Error: Nothing to change
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at /usr/src/app/src/device.js:162:17
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at tryCatcher (/usr/src/app/node_modules/bluebird/js/release/util.js:16:23)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Holder$3._callFunction (eval at generateHolderClass (/usr/src/app/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:14:44)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Holder$3.checkFulfillment (eval at generateHolderClass (/usr/src/app/node_modules/bluebird/js/release/join.js:92:16), <anonymous>:29:30)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise.eval (eval at thenCallback (/usr/src/app/node_modules/bluebird/js/release/join.js:14:16), <anonymous>:6:20)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._settlePromise (/usr/src/app/node_modules/bluebird/js/release/promise.js:566:21)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._settlePromise0 (/usr/src/app/node_modules/bluebird/js/release/promise.js:614:10)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._settlePromises (/usr/src/app/node_modules/bluebird/js/release/promise.js:693:18)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at Promise._fulfill (/usr/src/app/node_modules/bluebird/js/release/promise.js:638:18)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at /usr/src/app/node_modules/bluebird/js/release/nodeback.js:42:21
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at tryToString (fs.js:455:3)
Jun 09 21:40:35 8b758dc start-resin-supervisor[1046]:     at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:442:12)
```

[Forum](https://forums.resin.io/t/reset-config-variable-fleet-configuration-bug/1431/3)

### LINKED ISSUE #461: The off-line response of the /device api should include the commit hash
When a device is off-line the /device api still returns a response.  That response is currently missing the commit hash of the running container.  The information is available locally and it seems reasonable that it should be returned with the response even if the vpn connection to the resin data api's is unavailable.

Example off-line response:
```
{
  "ip_address": "10.1.1.182 192.168.254.1",
  "api_port": 48484,
  "os_version": "Resin OS 2.0.0-beta.7",
  "supervisor_version": "3.0.1",
  "download_progress": null,
  "update_pending": false,
  "update_failed": false,
  "update_downloaded": false
}
```

### LINKED ISSUE #487: Supervisor does not retry apiKey exchange when fails, and throws exception
It can happen that they apiKey -> deviceApiKey exchange does not succeed e.g. for network issues when the supervisor is starting up, but seems like the supervisor does not retry the exchange, instead errors out with things like:

```
Unhandled rejection t: Couldn't fetch device with provisioning key
    at /usr/src/app/dist/app.js:80:17531
    at r (/usr/src/app/dist/app.js:1:2435)
    at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:294:42283)
    at i._settlePromise (/usr/src/app/dist/app.js:294:43083)
    at i._settlePromise0 (/usr/src/app/dist/app.js:294:43782)
    at i._settlePromises (/usr/src/app/dist/app.js:294:45109)
    at i._fulfill (/usr/src/app/dist/app.js:294:44152)
    at i._resolveCallback (/usr/src/app/dist/app.js:294:41023)
    at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:294:42437)
    at i._settlePromise (/usr/src/app/dist/app.js:294:43083)
    at i._settlePromise0 (/usr/src/app/dist/app.js:294:43782)
    at i._settlePromises (/usr/src/app/dist/app.js:294:45109)
    at i._fulfill (/usr/src/app/dist/app.js:294:44152)
    at i._settlePromise (/usr/src/app/dist/app.js:294:43281)
```

### LINKED ISSUE #506: update-lock is ignored when changing boot `RESIN_HOST_CONFIG` variables
When those variables are added, the device reboots regardless of the update-lock status. (seen it on resinOS 1.26.0 / supervisor 4.1.2, haven't tested others yet)

Front logo [Front conversations](https://app.frontapp.com/open/top_34k9)

### LINKED ISSUE #531: Handle invalid RESIN_APP_RESTART_POLICY values
There was a user setting this variable to `true`, causing the following error:

```
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]: [2017-12-07T16:18:25.423Z] Error: Error: Invalid restart policy: true
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at _ (/usr/src/app/dist/app.js:528:9431)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at /usr/src/app/dist/app.js:528:7964
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r (/usr/src/app/dist/app.js:1:2393)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:289:20446)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise (/usr/src/app/dist/app.js:289:21246)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise0 (/usr/src/app/dist/app.js:289:21945)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromises (/usr/src/app/dist/app.js:289:23272)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r._drainQueue (/usr/src/app/dist/app.js:289:26274)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r._drainQueues (/usr/src/app/dist/app.js:289:26335)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at Immediate.drainQueues (/usr/src/app/dist/app.js:289:24478)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at runCallback (timers.js:574:20)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at tryOnImmediate (timers.js:554:5)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at processImmediate [as _immediateCallback] (timers.js:533:5) Error: Invalid restart policy: true
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at _ (/usr/src/app/dist/app.js:528:9431)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at /usr/src/app/dist/app.js:528:7964
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r (/usr/src/app/dist/app.js:1:2393)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:289:20446)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise (/usr/src/app/dist/app.js:289:21246)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise0 (/usr/src/app/dist/app.js:289:21945)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromises (/usr/src/app/dist/app.js:289:23272)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r._drainQueue (/usr/src/app/dist/app.js:289:26274)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r._drainQueues (/usr/src/app/dist/app.js:289:26335)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at Immediate.drainQueues (/usr/src/app/dist/app.js:289:24478)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at runCallback (timers.js:574:20)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at tryOnImmediate (timers.js:554:5)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at processImmediate [as _immediateCallback] (timers.js:533:5)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]: [2017-12-07T16:18:25.425Z] Scheduling another update attempt due to failure:  30000 Error: 1 error: Invalid restart policy: true
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at /usr/src/app/dist/app.js:528:19169
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at r (/usr/src/app/dist/app.js:1:2393)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:289:20446)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise (/usr/src/app/dist/app.js:289:21246)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise0 (/usr/src/app/dist/app.js:289:21945)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromises (/usr/src/app/dist/app.js:289:23272)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._fulfill (/usr/src/app/dist/app.js:289:22315)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at s._resolve (/usr/src/app/dist/app.js:289:31316)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at s._filter (/usr/src/app/dist/app.js:289:62689)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at s._promiseFulfilled (/usr/src/app/dist/app.js:289:62341)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at s._iterate (/usr/src/app/dist/app.js:289:31137)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at s.t (/usr/src/app/dist/app.js:289:30612)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise (/usr/src/app/dist/app.js:289:21284)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromise0 (/usr/src/app/dist/app.js:289:21945)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._settlePromises (/usr/src/app/dist/app.js:289:23272)
Dec 07 16:18:25 9c0177b start-resin-supervisor[889]:     at i._fulfill (/usr/src/app/dist/app.js:289:22315)
```

Maybe worth showing a useful warning to the user and default to `always`?

Front logo [Front conversations](https://app.frontapp.com/open/top_58q1)

### LINKED ISSUE #559: Events are missing info whenever the info is a number
https://github.com/resin-io/resin-supervisor/blob/7e04b4aec0dca21389d6f57703c4511543782201/src/utils.coffee#L54

is causing properties to be `null` if it's a number, eg in `'Restarting application', appId`

### PR DESCRIPTION
**Pull request by pcarranzav**
This PR adds support for multicontainer applications, and refactors most of the supervisor. It is huge, but it fixes a variety of issues:

Closes #559 
Closes #531 
Closes #506 
Closes #487 
Closes #461
Closes #450 
Closes #439 
Closes #426 
Closes #423 
Closes #388 
Closes #358 
Closes #348 
Closes #226 
Closes #194 
Closes #115 
Closes #63 
Closes #52 
Closes #30 

Related specs:
Connects-to: https://github.com/resin-io/hq/pull/616
Connects-to: https://github.com/resin-io/hq/pull/734

Also connects-to:
* https://github.com/resin-io/hq/issues/1007
* https://github.com/resin-io/hq/issues/996 (image urls have changed)
* https://github.com/resin-io/hq/issues/991 (offline mode improved)
* https://github.com/resin-io/hq/issues/971
* https://github.com/resin-io/hq/issues/967 (containers with bridge networking)
* https://github.com/resin-io/hq/issues/948
* https://github.com/resin-io/hq/issues/850 (same as 226)
* https://github.com/resin-io/hq/issues/820
* https://github.com/resin-io/hq/issues/817 (config variables now are independent from app)
* https://github.com/resin-io/hq/issues/569
* https://github.com/resin-io/hq/issues/494
* https://github.com/resin-io/hq/issues/424 (labels to configure access to resin API and supervisor API)
* https://github.com/resin-io/hq/issues/383
* https://github.com/resin-io/hq/issues/307
* https://github.com/resin-io/hq/issues/226 (volumes will be deleted when an app is deleted)

It may connect to other issues, but that's what I could find so far.

### CODE REVIEW

**Comment by pcarranzav** [comment]
Getting closer, I think this is somewhat functional. I've rearranged into commits to make review less painful.
There's still several TODOs:

- [ ] Implement the adapted proxyvisor properly
- [ ] Improve on the features for services, like allowing links and other compose options, and accounting for them when checking for service dependencies
- [ ] Re-implement "purge" to delete and recreate a service's named volumes
- [ ] Implement configuration for named networks and allow services to use more than one network (for now it only allows using network-mode)
- [ ] Allow more complex options for service ports
- [ ] Ensure all of the compose options match what the state endpoint will send us
- [ ] Properly implement the database migration for supervisor updates, both for local and dependent legacy data.
- [ ] Test with a proper multicontainer target state, possibly setting up an integration test with a mocked Resin API?
- [ ] Switch to the v2 state endpoint to actually run multicontainer apps

**Comment by pcarranzav** [comment]
Reformulating the previous TODO list given the current status:
- [x] Implement the adapted proxyvisor properly *(@josephroberts is testing and improving, but basic implementation is written)*
- [x] Re-implement "purge" to delete and recreate an app's named volumes *(implemented only on v1 API for single-container apps for now)*
- [ ] Properly implement the database migration for supervisor updates, both for local and dependent legacy data.
- [ ] Ensure config.txt modification and saving default values works as expected.

These items should be enough for this PR to be backwards compatible with the current supervisor - so potentially we could merge it before having the v2 state endpoint ready.

These would then be the following steps to get a proper multicontainer supervisor - which could be done on a separate PR:
- [ ] Improve on the features for services, like allowing links and other compose options, and accounting for them when checking for service dependencies.
- [ ] Implement configuration for named networks and allow services to use more than one network (for now it only allows using network-mode).
- [ ] Ensure all of the compose options match what the state endpoint will send us.
- [ ] Allow more complex options for service ports.
- [ ] Implement v2 supervisor API for multicontainer app management, including v2 purge which can be a bit challenging.
- [ ] Test with a proper multicontainer target state, possibly setting up an integration test with a mocked Resin API?
- [ ] Switch to the v2 state endpoint to actually run multicontainer apps

**Comment by lekkas** [comment]
HQ: https://github.com/resin-io/hq/pull/616

File: src/api-binder.coffee [hunk 1]
```diff
@@ -0,0 +1,369 @@
...
+
+class APIBinderRouter
+	constructor: (@apiBinder) ->
+		{ @eventTracker } = @apiBinder
+		@router = express.Router()
+		@router.use(bodyParser.urlencoded(extended: true))
+		@router.use(bodyParser.json())
+		@router.post '/v1/update', (req, res) =>
+			@eventTracker.track('Update notification')
+			setImmediate =>
```
Comment (petrosagg) [inline src/api-binder.coffee]: You don't need `setImmediate` here

File: src/api-binder.coffee [hunk 2]
```diff
@@ -0,0 +1,369 @@
...
+					@_exchangeKeyAndGetDeviceOrRegenerate(opts)
+				else if !opts.registered_at?
+					console.log('New device detected. Provisioning...')
+					deviceRegister.register(opts)
+					.timeout(opts.apiTimeout)
+					.catch DuplicateUuidError, =>
+						console.log('UUID already registered, trying a key exchange')
+						@_exchangeKeyAndGetDeviceOrRegenerate(opts)
+					.tap ->
+						opts.registered_at = Date.now()
```
Comment (petrosagg) [inline src/api-binder.coffee]: what if the device has not NTP yet?

File: src/application-manager.coffee [hunk 3]
```diff
@@ -0,0 +1,875 @@
...
+module.exports = class ApplicationManager extends EventEmitter
+	constructor: ({ @logger, @config, @db, @eventTracker }) ->
+		@docker = new Docker()
+		@images = new Images({ @docker, @logger, @db })
+		@services = new ServiceManager({ @docker, @logger, @images, @config })
+		@networks = new Networks({ @docker, @logger })
+		@volumes = new Volumes({ @docker, @logger })
+		@proxyvisor = new Proxyvisor({ @config, @logger, @db, @docker, @images, applications: this })
+		@_targetVolatilePerServiceId = {}
+		@validActions = [
```
Comment (petrosagg) [inline src/application-manager.coffee]: This information is duplicated in the function names bellow. They should be in one place so that when the function name changes all references to it change too

File: src/application-manager.coffee [hunk 4]
```diff
@@ -0,0 +1,875 @@
...
+		Promise.join(
+			@services.getStatus()
+			@images.getStatus()
+			(services, images) ->
+				apps = {}
+				dependent = {}
+				commit = null
+				# We iterate over the current running services and add them to the current state
+				# of the app they belong to.
+				_.forEach services, (service) ->
```
Comment (petrosagg) [inline src/application-manager.coffee]: This can be a simple for loop

File: src/application-manager.coffee [hunk 5]
```diff
@@ -0,0 +1,875 @@
...
+						commit = service.commit
+					else if commit != service.commit
+						commit = false
+					if !apps[appId].services[service.imageId]?
+						apps[appId].services[service.imageId] = _.pick(service, [ 'status', 'releaseId' ])
+						apps[appId].services[service.imageId].download_progress = null
+					else
+						# There's two containers with the same imageId, so this has to be a handover
+						previousReleaseId = apps[appId].services[service.imageId].releaseId
+						apps[appId].services[service.imageId].releaseId = Math.max(parseInt(previousReleaseId), parseInt(service.releaseId)).toString()
```
Comment (petrosagg) [inline src/application-manager.coffee]: Why do we store ids as strings?

File: src/application-manager.coffee [hunk 6]
```diff
@@ -0,0 +1,875 @@
...
+			targetServiceIds = _.map(targetServices, 'serviceId')
+			currentServiceIds = _.uniq(_.map(currentServices, 'serviceId'))
+
+			toBeRemoved = _.difference(currentServiceIds, targetServiceIds)
+			_.forEach toBeRemoved, (serviceId) ->
+				servicesToRemove = _.filter(currentServices, (s) -> s.serviceId == serviceId)
+				_.map servicesToRemove, (service) ->
+					removePairs.push({
+						current: service
+						target: null
```
Comment (petrosagg) [inline src/application-manager.coffee]: Why do you pass `target: null` here since the collection only contains remove operations?

File: src/application-manager.coffee [hunk 7]
```diff
@@ -0,0 +1,875 @@
...
+						serviceId
+					})
+
+			toBeInstalled = _.difference(targetServiceIds, currentServiceIds)
+			_.forEach toBeInstalled, (serviceId) ->
+				servicesToInstall = _.filter(targetServices, (s) -> s.serviceId == serviceId)
+				_.map servicesToInstall, (service) ->
```
Comment (petrosagg) [inline src/application-manager.coffee]: This should be a for loop

File: src/application-manager.coffee [hunk 8]
```diff
@@ -0,0 +1,875 @@
...
+				_.map servicesToRemove, (service) ->
+					removePairs.push({
+						current: service
+						target: null
+						serviceId
+					})
+
+			toBeInstalled = _.difference(targetServiceIds, currentServiceIds)
+			_.forEach toBeInstalled, (serviceId) ->
+				servicesToInstall = _.filter(targetServices, (s) -> s.serviceId == serviceId)
```
Comment (petrosagg) [inline src/application-manager.coffee]: How can there be more than one service to install with a particular id?

File: src/application-manager.coffee [hunk 9]
```diff
@@ -0,0 +1,875 @@
...
+
+			toBeMaybeUpdated = _.intersection(targetServiceIds, currentServiceIds)
+			currentServicesPerId = {}
+			targetServicesPerId = {}
+			_.forEach toBeMaybeUpdated, (serviceId) ->
+				currentServiceContainers = _.filter currentServices, (service) ->
+					return service.serviceId == serviceId
+				targetServicesForId = _.filter targetServices, (service) ->
+					return service.serviceId == serviceId
+				throw new Error("Target state includes multiple services with serviceId #{serviceId}") if targetServicesForId.length > 1
```
Comment (petrosagg) [inline src/application-manager.coffee]: How can this happen?

File: src/application-manager.coffee [hunk 10]
```diff
@@ -0,0 +1,875 @@
...
+				targetServicesPerId[serviceId] = targetServicesForId[0]
+				if currentServiceContainers.length > 1
+					currentServicesPerId[serviceId] = _.maxBy(currentServiceContainers, 'createdAt')
```
Comment (petrosagg) [inline src/application-manager.coffee]: How can this happen? Also could it choose the wrong one due to a combination of NTP and reboots causing the timestamp of the new one to be less than the old one?

File: src/application-manager.coffee [hunk 11]
```diff
@@ -0,0 +1,875 @@
...
+					_.forEach _.without(currentServiceContainers, currentServicesPerId[serviceId]), (service) ->
+						removePairs.push({
+							current: service
+							target: null
+							serviceId
+						})
+				else
+					currentServicesPerId[serviceId] = currentServiceContainers[0]
+
+			Promise.filter toBeMaybeUpdated, (serviceId) ->
```
Comment (petrosagg) [inline src/application-manager.coffee]: This doesn't have to be a promise chain

File: src/application-manager.coffee [hunk 12]
```diff
@@ -0,0 +1,875 @@
...
+				_.forEach dependencies, (dependency) ->
+					if !_.some(changingPairs, (pair) -> pair.serviceId == dependency.serviceId)
+						steps.push(serviceAction('kill', dependency.serviceId, dependency))
+				return steps
+		else if target?
+			return [{ action: 'createNetworkOrVolume', model, target }]
+
+	_nextStepsForNetwork: ({ current, target }, currentApp, changingPairs) =>
+		dependencyComparisonFn = (service, current) ->
+			service.network_mode == current.name
```
Comment (petrosagg) [inline src/application-manager.coffee]: A service can be part of multiple networks at the same time. Why do we use `network_mode`? Docker compose has a `networks` field that is an array of networks

File: src/application-manager.coffee [hunk 13]
```diff
@@ -0,0 +1,875 @@
...
+		@_nextStepsForNetworkOrVolume({ current, target }, currentApp, changingPairs, dependencyComparisonFn, 'network')
+
+	_nextStepsForVolume: ({ current, target }, currentApp, changingPairs) ->
+		# Check none of the currentApp.services use this network or volume
+		dependencyComparisonFn = (service, current) ->
+			_.some service.volumes, (volumeDefinition) ->
+				sourceName = volumeDefinition.split(':')[0]
```
Comment (petrosagg) [inline src/application-manager.coffee]: This will cause a normal volume to be incorectly interpreted as a named volume

File: src/application-manager.coffee [hunk 14]
```diff
@@ -0,0 +1,875 @@
...
+
+	_nextStepsForAppUpdate: (currentApp, targetApp, availableImages = [], stepsInProgress = []) =>
+		emptyApp = { services: [], volumes: {}, networks: {} }
+		if !targetApp?
+			targetApp = emptyApp
+		if !currentApp?
+			currentApp = emptyApp
+		appId = targetApp.appId ? currentApp.appId
+		# Create the default network for the target app
+		targetApp.networks[targetApp.appId] ?= {}
```
Comment (petrosagg) [inline src/application-manager.coffee]: If the targetApp is undefined then this will create a network?

File: src/application-manager.coffee [hunk 15]
```diff
@@ -0,0 +1,875 @@
...
+		Promise.join(
+			@compareNetworksOrVolumesForUpdate(@networks, { current: currentApp.networks, target: targetApp.networks }, appId)
+			@compareNetworksOrVolumesForUpdate(@volumes, { current: currentApp.volumes, target: targetApp.volumes }, appId)
```
Comment (petrosagg) [inline src/application-manager.coffee]: I suggest creating two separate functions called `compareNetworksForUpdate` and `compareVolumesForUpdate` that use the right data internally and not leave this responsibility to the caller

File: src/application-manager.coffee [hunk 16]
```diff
@@ -0,0 +1,875 @@
...
+					steps.push(serviceAction('kill', current.serviceId, current, null))
+				# next step for install pairs in download - start order, but start requires dependencies, networks and volumes met
+				# next step for update pairs in order by update strategy. start requires dependencies, networks and volumes met.
+				_.forEach installPairs.concat(updatePairs), (pair) =>
+					step = @_nextStepForService(pair, { targetApp, networkPairs, volumePairs, installPairs, updatePairs, stepsInProgress, availableImages })
+					steps.push(step) if step?
+				# next step for network pairs - remove requires services killed, create kill if no pairs or steps affect that service
+				_.forEach networkPairs, (pair) =>
+					pairSteps = @_nextStepsForNetwork(pair, currentApp, removePairs.concat(updatePairs))
+					steps = steps.concat(pairSteps) if !_.isEmpty(pairSteps)
```
Comment (petrosagg) [inline src/application-manager.coffee]: Why do we need to check if the `pairSteps` are empty? Concatenating an empty array is a no-op so you don't need the special case

File: src/application-manager.coffee [hunk 17]
```diff
@@ -0,0 +1,875 @@
...
+				# next step for volume pairs - remove requires services killed, create kill if no pairs or steps affect that service
+				_.forEach volumePairs, (pair) =>
+					pairSteps = @_nextStepsForVolume(pair, currentApp, removePairs.concat(updatePairs))
+					steps = steps.concat(pairSteps) if !_.isEmpty(pairSteps)
```
Comment (petrosagg) [inline src/application-manager.coffee]: Same here

File: src/application-manager.coffee [hunk 18]
```diff
@@ -0,0 +1,875 @@
...
+	setTarget: (apps, dependent , trx) =>
+		setInTransaction = (trx) =>
+			Promise.try =>
+				if apps?
+					appsArray = _.map apps, (app, appId) ->
+						appClone = _.clone(app)
+						appClone.appId = appId
+						return appClone
+					Promise.map(appsArray, @normaliseAppForDB)
+					.then (appsForDB) =>
```
Comment (petrosagg) [inline src/application-manager.coffee]: You can do `.map` directly here

File: src/application-manager.coffee [hunk 19]
```diff
@@ -0,0 +1,875 @@
...
+
+	# return images that:
+	# - are not used in the current state, and
+	# - are not going to be used in the target state, and
+	# - are not needed for delta source / pull caching or would be used for a service with delete-then-download as strategy
+	_unnecessaryImages: (current, target, available) =>
+
+		allImagesForApp = (app) -> _.map(app.services, imageForService)
+
+		currentImages = _.flatten(_.map(current.local?.apps, allImagesForApp))
```
Comment (petrosagg) [inline src/application-manager.coffee]: What happens if `current.local` is undefined and how can this happen?

File: src/application-manager.coffee [hunk 20]
```diff
@@ -0,0 +1,875 @@
...
+		targetImages = _.flatten(_.map(target.local?.apps, allImagesForApp))
```
Comment (petrosagg) [inline src/application-manager.coffee]: Same here for `target.local`

File: src/application-manager.coffee [hunk 21]
```diff
@@ -0,0 +1,875 @@
...
+		Promise.try =>
+			currentByAppId = _.keyBy(current.local.apps ? [], 'appId')
+			targetByAppId = _.keyBy(target.local.apps ? [], 'appId')
+			nextSteps = []
+			if !_.some(stepsInProgress, (step) -> step.action == 'fetch')
+				if cleanupNeeded
+					nextSteps.push({ action: 'cleanup' })
+				imagesToRemove = @_unnecessaryImages(current, target, availableImages)
+				_.forEach imagesToRemove, (image) ->
+					nextSteps.push({ action: 'removeImage', image })
```
Comment (petrosagg) [inline src/application-manager.coffee]: when the first image is removed, `_inferNextSteps` will re-run and the image removal steps will be re-added

File: src/compose/service.coffee [hunk 22]
```diff
@@ -0,0 +1,343 @@
...
+		_.forEach container.Config.ExposedPorts, (conf, port) ->
+			containerPort = port.match(/^([0-9]*)\/tcp$/)?[1]
+			if containerPort? and !_.includes(boundContainerPorts, containerPort)
+				expose.push(containerPort)
+
+		appId = container.Config.Labels['io.resin.app_id']
+		serviceId = container.Config.Labels['io.resin.service_id']
+		serviceName = container.Config.Labels['io.resin.service_name']
+		releaseId = container.Name.match(/.*_(\d+)$/)?[1]
+		service = {
```
Comment (petrosagg) [inline src/compose/service.coffee]: This object has inconsistent casing. Some are camelCase some snake_case

File: src/device-state.coffee [hunk 23]
```diff
@@ -0,0 +1,512 @@
...
+			force = validation.checkTruthy(req.body.force)
+			@deviceState.executeStepAction({ action: 'reboot' }, { force })
+			.then (response) ->
+				res.status(202).json(response)
+			.catch (err) ->
+				if err instanceof updateLock.UpdatesLockedError
+					status = 423
+				else
+					status = 500
+				res.status(status).json({ Data: '', Error: err?.message or err or 'Unknown error' })
```
Comment (petrosagg) [inline src/device-state.coffee]: Why does the return object look like Go serialised it? (i.e `Data` instead of `data`)

File: src/device-state.coffee [hunk 24]
```diff
@@ -0,0 +1,512 @@
...
+	constructor: ({ @db, @config, @eventTracker }) ->
+		@logger = new Logger({ @eventTracker })
+		@deviceConfig = new DeviceConfig({ @db, @config, @logger })
+		@applications = new ApplicationManager({ @config, @logger, @db, @eventTracker })
+		@on 'error', (err) ->
+			console.error('Error in deviceState: ', err, err.stack)
+		@_currentVolatile = {}
+		_lock = new Lock()
+		@_writeLock = Promise.promisify(_lock.async.writeLock)
+		@_readLock = Promise.promisify(_lock.async.writeLock)
```
Comment (petrosagg) [inline src/device-state.coffee]: Did you mean `_lock.async.readLock` here?

File: src/device-state.coffee [hunk 25]
```diff
@@ -0,0 +1,512 @@
...
+		, @config.constants.ipAddressUpdateInterval
+
+	saveInitialConfig: =>
+		@deviceConfig.getCurrent()
+		.then (devConf) =>
+			@deviceConfig.setTarget(devConf)
+		.then =>
+			@config.set({ initialConfigSaved: 'true' })
+
+	emitAsync: (ev, args...) =>
```
Comment (petrosagg) [inline src/device-state.coffee]: why does emit have to be async?

File: src/device-state.coffee [hunk 26]
```diff
@@ -0,0 +1,512 @@
...
+		setImmediate => @emit(ev, args...)
+
+	readLockTarget: =>
```
Comment (petrosagg) [inline src/device-state.coffee]: This will expose the release callback to the caller. Change these functions to accept the function to be run under the lock and handle locking and releasing internally

File: src/device-state.coffee [hunk 27]
```diff
@@ -0,0 +1,512 @@
...
+					@scheduledApply = null
+			else
+				# If a delay has been set it's because we need to hold off before applying again,
+				# so we need to respect the maximum delay that has been passed
+				@scheduledApply.delay = Math.max(delay, @scheduledApply.delay)
+				@scheduledApply.force or= force
+			return
+		@applyInProgress = true
+		setTimeout( =>
+			@applyTarget({ force })
```
Comment (petrosagg) [inline src/device-state.coffee]: Instead of using the event emitter and conditionally adding `.once` handlers you can instead put a `.finally` here and if `@scheduledApply` is set, re-run. This way you avoid having to deal with event handlers above

File: src/device-state.coffee [hunk 28]
```diff
@@ -0,0 +1,512 @@
...
+			release()
+
+	setTarget: (target) ->
+		validateState(target)
+		.then =>
+			Promise.using @writeLockTarget(), =>
+				# Apps, deviceConfig, dependent
+				@db.transaction (trx) =>
+					Promise.try =>
+						@config.set({ name: target.local.name }, trx) if target.local?.name?
```
Comment (petrosagg) [inline src/device-state.coffee]: How can `target.local` be undefined?

File: src/compose/images.coffee [hunk 29]
```diff
@@ -0,0 +1,195 @@
...
+		@inspectByName(image.name)
+		.catch ImageNotFoundError, (err) ->
+			removed = false
+			return null
+		.then (img) =>
+			if img?
+				@db.models('image').where(name: image.name).select()
+				.then (imagesFromDB) =>
+					if imagesFromDB.length == 1 and _.isEqual(@format(imagesFromDB[0]), @format(image))
+						@docker.getImage(image.name).remove(force: true)
```
Comment (petrosagg) [inline src/compose/images.coffee]: You can move the `.catch()` here and remove both the `removed` flag and the `if img?` check in the previous block

File: src/compose/images.coffee [hunk 30]
```diff
@@ -0,0 +1,195 @@
...
+					@docker.getRegistryAndName(repoTag)
+					.then ({ imageName, tagName }) ->
+						if imageName == supervisorImageInfo.imageName and tagName != supervisorImageInfo.tagName
+							images.push(repoTag)
+		.then =>
+			@docker.listImages(filters: { dangling: [ 'true' ] })
+			.map (image) ->
+				images.push(image.Id)
+		.then =>
+			return _.filter images, (image) =>
```
Comment (petrosagg) [inline src/compose/images.coffee]: nit: remove return

File: src/compose/images.coffee [hunk 31]
```diff
@@ -0,0 +1,195 @@
...
+				!@imageCleanupFailures[image]? or Date.now() - @imageCleanupFailures[image] > 3600 * 1000
```
Comment (petrosagg) [inline src/compose/images.coffee]: Should this timeout value be in constants?

File: src/compose/images.coffee [hunk 32]
```diff
@@ -0,0 +1,195 @@
...
+
+	inspectByName: (imageName) =>
```
Comment (petrosagg) [inline src/compose/images.coffee]: is it really worth wrapping these methods?

File: src/compose/networks.coffee [hunk 33]
```diff
@@ -0,0 +1,56 @@
...
+		@docker.listNetworks(filters: label: [ 'io.resin.supervised' ])
+		.then (networks) =>
+			Promise.map networks, (network) =>
+				@docker.getNetwork(network.Name).inspect()
+				.then (net) =>
+					@format(net)
+
+	getAllByAppId: (appId) =>
+		@getAll()
+		.then (networks) ->
```
Comment (petrosagg) [inline src/compose/networks.coffee]: You can use bluebird's filter

File: src/compose/networks.coffee [hunk 34]
```diff
@@ -0,0 +1,56 @@
...
+			_.filter(networks, (v) -> v.appId == appId)
+
+	get: (name) =>
+		@docker.getNetwork(name).inspect()
+		.then (network) ->
+			return @format(network)
```
Comment (petrosagg) [inline src/compose/networks.coffee]: nit: no return here

File: src/compose/networks.coffee [hunk 35]
```diff
@@ -0,0 +1,56 @@
...
+
+	remove: ({ name }) =>
+		@logger.logSystemEvent(logTypes.removeNetwork, { network: { name } })
+		@docker.getNetwork(name).remove()
+		.catch (err) =>
+			@logger.logSystemEvent(logTypes.removeNetworkError, { network: { name }, error: err })
+			throw err
+
+	isEqualConfig: (current, target) ->
+		return true
```
Comment (petrosagg) [inline src/compose/networks.coffee]: What?

File: src/compose/service-manager.coffee [hunk 36]
```diff
@@ -0,0 +1,276 @@
...
+		@listening = false
+		# Volatile state of containers, indexed by containerId (or random strings if we don't have a containerId yet)
+		@volatileState = {}
+
+	killAllLegacy: =>
+		# Containers haven't been normalized (this is an updated supervisor)
+		# so we need to stop and remove them
+		@docker.getImage(constants.supervisorImage).inspect()
+		.then (supervisorImage) =>
+			Promise.map(@docker.listContainers(all: true), (container) =>
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: nit: remove extra brackets of Promise.map

File: src/compose/service-manager.coffee [hunk 37]
```diff
@@ -0,0 +1,276 @@
...
+				@docker.getImage(container.Image).inspect()
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Docker 1.8 and above includes `ImageID` in the container list response. If we don't support earlier versions you can remove the inspect

File: src/compose/service-manager.coffee [hunk 38]
```diff
@@ -0,0 +1,276 @@
...
+
+	_killContainer: (containerId, service = {}, { removeContainer = true }) =>
+		@logger.logSystemEvent(logTypes.stopService, { service })
+		@reportNewStatus(containerId, service, 'Stopping') if service.imageId?
+		containerObj = @docker.getContainer(containerId)
+		containerObj.stop(t: 10)
+		.then ->
+			containerObj.remove(v: true) if removeContainer
+		.catch (err) =>
+			# Get the statusCode from the original cause and make sure statusCode its definitely a string for comparison
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: typo: its -> is

File: src/compose/service-manager.coffee [hunk 39]
```diff
@@ -0,0 +1,276 @@
...
+			# reasons.
+			statusCode = '' + err.statusCode
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Why not make it a number since you compare it with numbers?

File: src/compose/service-manager.coffee [hunk 40]
```diff
@@ -0,0 +1,276 @@
...
+	kill: (service, { removeContainer = true } = {}) =>
+		@_killContainer(service.containerId, service, { removeContainer })
+		.then ->
+			service.running = false
+			return service
+
+	getAllByAppId: (appId) =>
+		@getAll("io.resin.app_id=#{appId}")
+		.filter (service) ->
+			service.appId == appId
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Why is the extra filtering needed? Isn't the label filter enough?

File: src/compose/service-manager.coffee [hunk 41]
```diff
@@ -0,0 +1,276 @@
...
+	getAll: (extraLabelFilters = []) =>
+		filters = label: [ 'io.resin.supervised' ].concat(extraLabelFilters)
+		@docker.listContainers({ all: true, filters })
+		.then (containers) =>
+			Promise.mapSeries containers, (container) =>
+				@docker.getContainer(container.Id).inspect()
+				.then(Service.fromContainer)
+
+	# Returns an array with the container(s) matching a service by appId, commit, image and environment
+	get: (service) =>
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: This should be named `getAllByServiceId` to be consistent with `getAllByAppId`

File: src/compose/service-manager.coffee [hunk 42]
```diff
@@ -0,0 +1,276 @@
...
+		@getAll("io.resin.service_id=#{service.serviceId}")
+		.then (services = []) ->
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Why is this defaulting to an array? `getAll` should always return an array

File: src/compose/service-manager.coffee [hunk 43]
```diff
@@ -0,0 +1,276 @@
...
+			return _.filter services, (currentService) ->
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Why are you not using a Bluebird filter like above?

File: src/compose/service-manager.coffee [hunk 44]
```diff
@@ -0,0 +1,276 @@
...
+				currentService.isSameContainer(service)
+
+	getStatus: =>
+		@getAll()
+		.then (services) =>
+			status = _.clone(@volatileState)
+			_.forEach services, (service) ->
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: for loop instead of forEach

File: src/compose/service-manager.coffee [hunk 45]
```diff
@@ -0,0 +1,276 @@
...
+				status[service.containerId] ?= _.pick(service, [ 'appId', 'imageId', 'status', 'releaseId', 'commit' ])
+			return _.values(status)
+
+	getByDockerContainerId: (containerId) =>
+		@docker.getContainer(containerId).inspect()
+		.then (container) ->
+			if !container.Config.Labels['io.resin.supervised']?
+				return null
+			return Service.fromContainer(container)
+		.catchReturn(null)
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Why is this hiding an error?

File: src/compose/service-manager.coffee [hunk 46]
```diff
@@ -0,0 +1,276 @@
...
+			killme = service.killmeFullPathOnHost()
+			fs.statAsync(killme)
+			.catch (err) ->
+				throw err unless (Date.now() - startTime) > timeout
+			.then ->
+				fs.unlinkAsync(killme).catch(_.noop)
+		retryCheck = ->
+			checkFileOrTimeout()
+			.catch ->
+				Promise.delay(pollInterval).then(retryCheck)
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: This function looks quite complex with two promise chains going on and a mix of errors/non-errors to signal completion. I suggest rewriting to this:

```coffeescript
waitToKill: (service, timeout) ->                                                                                                                                        
    pollInterval = 100 
    timeout = checkInt(timeout, positive: true) ? 60000
    deadline = Date.now() + timeout

    killmePath = service.killmeFullPathOnHost()

    wait = ->
        fs.statAsync(killme)
        .then ->
            fs.unlinkAsync(killme).catch(_.noop)
        .catch (err) ->
            if Date.now() < deadline
                Promise.delay(pollInterval).then(checkFileOrTimeout)
    wait()
```

File: src/compose/service-manager.coffee [hunk 47]
```diff
@@ -0,0 +1,276 @@
...
+		retryCheck()
+
+	prepareForHandover: (service) =>
+		@get(service)
+		.then ([ svc ]) =>
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: What if this returns multiple services? Should there be a method that explicitly returns one service?

File: src/compose/service-manager.coffee [hunk 48]
```diff
@@ -0,0 +1,276 @@
...
+			@waitToKill(currentService, targetService.labels['io.resin.update.handover_timeout'])
+		.then =>
+			@kill(currentService)
+
+	listenToEvents: =>
+		return if @listening
+		@listening = true
+		@docker.getEvents(filters: type: [ 'container' ])
+		.then (stream) =>
+			parser = new JSONParser()
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: This pipeline looks weird with all this manual setup, casting to buffers, and "data" event listeners which disable stream backpressure.

Let's switch to `JSONStream` and `event-stream`. See here for how to set it up https://github.com/resin-io/docker-storage-gc/blob/v1.2.0/lib/docker-event-stream.coffee#L15-L26

File: src/compose/service-manager.coffee [hunk 49]
```diff
@@ -0,0 +1,276 @@
...
+			parser.onError = (err) ->
+				console.error('Error on docker events stream', err, err.stack)
+				stream.destroy()
+			parser.onValue = (data) =>
+				return if parser.stack.length != 0
+				if data?.status in ['die', 'start']
+					setImmediate =>
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Why do you `setImmediate` here?

File: src/compose/service-manager.coffee [hunk 50]
```diff
@@ -0,0 +1,276 @@
...
+						@getByDockerContainerId(data.id)
+						.then (service) =>
+							if service?
+								if data.status == 'die'
+									@logger.logSystemEvent(logTypes.serviceExit, { service })
+									@containerHasDied[data.id] = true
+								else if data.status == 'start' and @containerHasDied[data.id]
+									@logger.logSystemEvent(logTypes.serviceRestart, { service })
```
Comment (petrosagg) [inline src/compose/service-manager.coffee]: Should this also clear the flag from `@containerHasDied`?

File: src/compose/service.coffee [hunk 51]
```diff
@@ -0,0 +1,343 @@
+_ = require 'lodash'
+path = require 'path'
+{ checkTruthy, checkInt } = require '../lib/validation'
+updateLock = require '../lib/update-lock'
+constants = require '../lib/constants'
+conversions =  require '../lib/conversions'
+
+validRestartPolicies = [ 'no', 'always', 'on-failure', 'unless-stopped' ]
```
Comment (petrosagg) [inline src/compose/service.coffee]: "no" isn't a valid policy

File: src/compose/volumes.coffee [hunk 52]
```diff
@@ -0,0 +1,108 @@
...
+migration = require '../lib/migration'
+constants = require '../lib/constants'
+
+ENOENT = (err) -> err.code is 'ENOENT'
+
+module.exports = class Volumes
+	constructor: ({ @docker, @logger }) ->
+
+	format: (volume) ->
+		appId = volume.Labels['io.resin.app_id']
```
Comment (petrosagg) [inline src/compose/volumes.coffee]: shouldn't this be converted to a number?

File: src/compose/volumes.coffee [hunk 53]
```diff
@@ -0,0 +1,108 @@
...
+			throw err
+
+	createFromLegacy: (appId) =>
+		name = migration.defaultLegacyVolume(appId)
+		@create({ name, appId })
+		.then (v) ->
+			v.inspect()
+		.then (v) ->
+			volumePath = "#{constants.rootMountPoint}#{v.Mountpoint}"
+			legacyPath = "/mnt/root/resin-data/#{appId}"
```
Comment (petrosagg) [inline src/compose/volumes.coffee]: Use path.join to join two paths. https://nodejs.org/api/path.html#path_path_join_paths

File: src/compose/volumes.coffee [hunk 54]
```diff
@@ -0,0 +1,108 @@
...
+			fs.lstatAsync(legacyPath)
```
Comment (petrosagg) [inline src/compose/volumes.coffee]: All you need to do here is the following (transformed in async code):

```coffeescript
fs.rename(legacyPath, volumePath)
parent = fs.open(path.dirname(volumePath)))
fs.fsync(parent)
fs.close(parent)
```

File: src/db.coffee [hunk 55]
```diff
@@ -1,113 +1,228 @@
...
+					t.dropColumn(column)
+
+	dropTableIfExists: (tableName, trx) =>
+		knex = trx ? @knex
+		knex.schema.hasTable(tableName)
+		.then (exists) ->
+			knex.schema.dropTable(tableName) if exists
+
+	_migrateToV2: =>
+		# Drop all tables, but keep the info we need
```
Comment (petrosagg) [inline src/db.coffee]: migration should happen atomically. This method will commit the tx before the new schema is in place

File: src/device-state.coffee [hunk 56]
```diff
@@ -0,0 +1,512 @@
...
+				JSON.parse(j)
+			catch
+				{}
+		tryParseArray = (j) ->
+			try
+				JSON.parse(j)
+			catch
+				[]
+
+		dependentDevices = tryParseArray(dependentDevices)
```
Comment (petrosagg) [inline src/device-state.coffee]: How can failing to parse this not be fatal?

File: src/api-binder.coffee (hunk 1 above)
Comment (pcarranzav) [reply src/api-binder.coffee]: Done

File: src/api-binder.coffee (hunk 2 above)
Comment (pcarranzav) [reply src/api-binder.coffee]: We don't really care as this is actually a legacy value and no one really reads the actual datetime - it might as well just be a boolean saying whether the device is registered or not. But since previously registered devices from older versions will have this key, we maintain compatibility. If anyone wants to use this (which they shouldn't since we never documented its meaning), they should at least know that this is device time.

File: src/application-manager.coffee (hunk 3 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Done

File: src/application-manager.coffee (hunk 4 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Done (and in a bunch of other places too). I actually like the _.forEach because it abstracts the loop and works consistently for arrays and objects. But I've removed them in almost all places, only left it when iterating over objects or when the use of a function gave a clear benefit (imo) to the resulting code.

File: src/application-manager.coffee (hunk 5 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Working to change that... we've been doing historically and it had the benefit of making it simpler when using the ids as keys to a map. Now we'll have to be more careful when comparing ids that might have been keys to a map (as they would've been "cast" to string when used as a key)

File: src/application-manager.coffee (hunk 6 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: For consistency, I want all the collections returned by this method to have current, target and serviceId.

File: src/application-manager.coffee (hunk 8 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Fixed (rationale was that the target state could be set by a source that doesn't quite validate things like this, but this is not necessary after what we discussed)

File: src/application-manager.coffee (hunk 7 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Fixed

File: src/application-manager.coffee (hunk 9 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: It can't, so fixed
(Again, it was meant to catch a possibly invalid target state)

File: src/application-manager.coffee (hunk 10 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: This can happen in rare scenarios, like an unexpected poweroff while doing a handover. I figured choosing the latest should be a reasonable best effort - both this case being hit *and* an ntp issue at the same time seems rare enough not to care?

File: src/application-manager.coffee (hunk 11 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Fixed

File: src/application-manager.coffee (hunk 12 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: This is one of the TODOs on my list (managing several `networks` is a bit more complex)

File: src/application-manager.coffee (hunk 13 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Fixed (though it wouldn't have really caused problems, since the name would never have matched a named volume's name)

File: src/application-manager.coffee (hunk 14 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Good catch, and Shaun was actually hitting this. Fixed.

File: src/application-manager.coffee (hunk 16 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Done

File: src/application-manager.coffee (hunk 17 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Done

File: src/application-manager.coffee (hunk 18 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Not really, cause we also use appsForDB as a collection in line 687 below (we could `return app` inside the map, but then it kinda defeats the purpose of using the .map)

File: src/application-manager.coffee (hunk 19 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Should never happen really, so fixed

File: src/application-manager.coffee (hunk 20 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Same

File: src/application-manager.coffee (hunk 21 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Fixed by making the `@_removeDuplicateSteps` also affect these steps

File: src/compose/service.coffee (hunk 22 above)
Comment (pcarranzav) [reply src/compose/service.coffee]: This is because some fields come from the compose yaml snake_cased, and we use camelCase for everything else... I guess the best way to address this is to have the builder change everything to camelCase in its compose.yml parser - so I'll defer this until we have a way forward on that unified parser and how it works, sound ok?

File: src/db.coffee [hunk 57]
```diff
@@ -1,113 +1,228 @@
...
+
+	# Returns a knex object for one of the models (tables)
+	models: (modelName) =>
+		@knex(modelName)
+
+	upsertModel: (modelName, obj, id, trx) =>
+		knex = trx ? @knex
+		knex(modelName).update(obj).where(id)
+		.then (n) ->
+			knex(modelName).insert(obj) if n == 0
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/db.coffee]: Fixed all around the code

File: src/device-state.coffee (hunk 23 above)
Comment (pcarranzav) [reply src/device-state.coffee]: Cause in non-error cases the response comes from gosuper that uses that format, and this is a legacy endpoint that has to respect that format (as much as possible, at least).
v2 endpoints will not have this problem.

File: src/device-state.coffee (hunk 24 above)
Comment (pcarranzav) [reply src/device-state.coffee]: Ah, yeah, fixed

File: src/device-state.coffee (hunk 25 above)
Comment (pcarranzav) [reply src/device-state.coffee]: It doesn't *have* to be, but emit regularly blocks on any listeners and I wouldn't want this behavior for our emitters, so the easiest way of doing this consistently is to always use this emitAsync.

File: src/device-state.coffee (hunk 26 above)
Comment (pcarranzav) [reply src/device-state.coffee]: Done, here and in the update lock calls in ApplicationManager

File: src/device-state.coffee (hunk 28 above)
Comment (pcarranzav) [reply src/device-state.coffee]: Fixed (again, this was meant to allow setting parts of the target state separately).

File: src/device-state.coffee (hunk 27 above)
Comment (pcarranzav) [reply src/device-state.coffee]: Working on this one... it's a bit more complicated than that because of the way applyTarget works - it doesn't return a promise that gets resolved when everything finishes. Instead several steps will run in parallel and whenever each of them finishes we use continueApplyTarget to schedule another run of applyTarget.

I'm quite sure I can make it work purely with promises but I need to think it through to avoid messing up.

File: src/compose/service-manager.coffee (hunk 48 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Yup, we originally used JSONStream and I had switched to using jsonnparse trying to solve what I solved with https://github.com/resin-io/resin-supervisor/pull/517 - forgot to revert the change, will do it

File: src/compose/images.coffee (hunk 29 above)
Comment (pcarranzav) [reply src/compose/images.coffee]: Nice one, done (and added a catchReturn to make it even simpler)

File: src/compose/images.coffee (hunk 30 above)
Comment (pcarranzav) [reply src/compose/images.coffee]: Done

File: src/compose/images.coffee (hunk 31 above)
Comment (pcarranzav) [reply src/compose/images.coffee]: Moved

File: src/compose/images.coffee (hunk 32 above)
Comment (pcarranzav) [reply src/compose/images.coffee]: Well, imo they don't hurt and allow other modules to have access to them without using the docker client directly, but I can remove it if you prefer. Same with `normalise` below, I suppose?

File: src/compose/networks.coffee (hunk 33 above)
Comment (pcarranzav) [reply src/compose/networks.coffee]: Done

File: src/compose/networks.coffee (hunk 34 above)
Comment (pcarranzav) [reply src/compose/networks.coffee]: Done

File: src/compose/networks.coffee (hunk 35 above)
Comment (pcarranzav) [reply src/compose/networks.coffee]: Again, this is TODO - together with supporting several networks per container, I'll implement the network config features that we want to support. Coming really soon. Marked it as TODO with a comment for now.

File: src/compose/service-manager.coffee (hunk 36 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Done

File: src/compose/service-manager.coffee (hunk 37 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Good one, done

File: src/compose/service-manager.coffee (hunk 38 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Fixed

File: src/compose/service-manager.coffee (hunk 39 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Done (it had been like that before my time, I suppose because dockerode might have sometimes returned numbers or strings? I added a checkInt just in case)

File: src/compose/service-manager.coffee (hunk 40 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Yup, I added the label filter later and forgot to remove this. Done.

File: src/compose/service-manager.coffee (hunk 41 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Not really, cause this doesn't just get by serviceId, it matches all of the container's config. And I refactored it to return only one service.

File: src/compose/service-manager.coffee (hunk 42 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Fixed

File: src/compose/service-manager.coffee (hunk 43 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Done

File: src/compose/service-manager.coffee (hunk 44 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Done

File: src/compose/service-manager.coffee (hunk 45 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: The idea was that a null result meant the container wasn't found (we've done this in other places in the past), but it's true that is ugly, so I changed it to not hide the error, and moved the catchReturn to the caller.

File: src/compose/service-manager.coffee (hunk 46 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Nice, done (almost copy paste, just a few details fixed)

File: src/compose/service-manager.coffee (hunk 47 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Fixed, made `get` return the first one it finds. It is actually a situation that might happen *because* of a handover, but it should never happen here.

File: src/compose/service-manager.coffee (hunk 49 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: To avoid returning the promise, but now I changed it to just have a return below.

File: src/compose/service-manager.coffee (hunk 50 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Yes. Done.

File: src/compose/service.coffee (hunk 51 above)
Comment (pcarranzav) [reply src/compose/service.coffee]: Oh, you're right! I thought that it was because it's a valid option in docker compose, and it's also what docker returns when you inspect a container without restart policy. I changed `toContainerConfig` to not set any restart policy in this case - but it's still a valid policy when it comes as an input to the Service constructor.

File: src/compose/volumes.coffee (hunk 52 above)
Comment (pcarranzav) [reply src/compose/volumes.coffee]: Now that we're using numbers for ids, yes. Done.

File: src/compose/volumes.coffee (hunk 53 above)
Comment (pcarranzav) [reply src/compose/volumes.coffee]: Done

File: src/compose/volumes.coffee (hunk 54 above)
Comment (pcarranzav) [reply src/compose/volumes.coffee]: I think I thought it wouldn't work because they are in different mounts... I've changed it, so will test it soon.

File: src/db.coffee (hunk 55 above)
Comment (pcarranzav) [reply src/db.coffee]: Yup, this is all changing to use knex migrations

File: src/device-state.coffee (hunk 56 above)
Comment (pcarranzav) [reply src/device-state.coffee]: Yeah, the idea was that really old supervisors might just not have a dependent devices table, so the dependentDevices we get here might be null, and we'd treat it as empty. In any case this is going away with knex migrations.

File: src/compose/service-manager.coffee (hunk 48 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Done (without event-stream, but it's almost exactly how we had it before)

**Comment by pcarranzav** [comment]
Main outstanding/todo items:
- finish switching to knex migrations
- implement multiple networks per service, besides networkMode
- implement configuration for networks (e.g. IPAM)
- refactor deviceState.triggerApplyTarget and deviceState.applyTarget to work with promises instead of events.
- figure out what to do with deltas given we can't tag using repo digests
^ @petrosagg so you know what to expect if you review

I haven't tested the latest changes so the latest build may be completely broken - I'll test and fix where appropriate after getting some sleep

**Comment by pcarranzav** [comment]
Just pushed 7e045fc which finishes the switch to knex migrations - haven't tested it on a device yet.
The previous 0cf4aaa seemed to run fine as far as I could tell (using a local sync to test).

**Comment by pcarranzav** [comment]
Update on main outstanding/todo items (some have been done, and there's others I forgot to mention before):

- ~~finish switching to knex migrations~~
- ~~implement multiple networks per service, besides networkMode~~
- implement configuration for networks (e.g. IPAM, aliases)
- refactor deviceState.triggerApplyTarget and deviceState.applyTarget to work with promises instead of events.
- figure out what to do with deltas given we can't tag using repo digests
- implement supervisor API v2 (I had forgotten about this in my previous list, and it's an important one)
- Adapt the healthcheck from #530 to multicontainer
- Implement the native-resin + pubnub logger
- check for additional compose features we can support

File: src/application-manager.coffee (hunk 15 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Done

File: src/compose/service.coffee (hunk 22 above)
Comment (pcarranzav) [reply src/compose/service.coffee]: Fixed with help from `_.camelCase`

File: src/application-manager.coffee [hunk 58]
```diff
@@ -0,0 +1,1047 @@
...
+		serviceId: service.serviceId
+	}
+
+pathExistsOnHost = (p) ->
+	fs.statAsync(path.join(constants.rootMountPoint, p))
+	.return(true)
+	.catchReturn(false)
+
+# TODO: implement additional v2 endpoints
+# v1 endpoins only work for single-container apps as they assume the app has a single service.
```
Comment (CameronDiver) [inline src/application-manager.coffee]: Is this comment still correct?

File: src/application-manager.coffee [hunk 59]
```diff
@@ -0,0 +1,1047 @@
...
+
+	init: =>
+		@images.cleanupDatabase()
+		.then =>
+			@services.attachToRunning()
+		.then =>
+			@services.listenToEvents()
+
+	# Returns the status of applications and their services
+	# TODO: discuss: I think commit could be deduced by the UI looking at the image_installs on the API?
```
Comment (CameronDiver) [inline src/application-manager.coffee]: I don't think we should worry about this just now, it will soon be a release ID anyway.

File: src/application-manager.coffee [hunk 60]
```diff
@@ -0,0 +1,1047 @@
...
+						releaseId = service.releaseId
+					else if releaseId != service.releaseId
+						releaseId = false
+					if !apps[appId].services[service.imageId]?
+						apps[appId].services[service.imageId] = _.pick(service, [ 'status', 'releaseId' ])
+						apps[appId].services[service.imageId].download_progress = null
+					else
+						# There's two containers with the same imageId, so this has to be a handover
+						previousReleaseId = apps[appId].services[service.imageId].releaseId
+						apps[appId].services[service.imageId].releaseId = Math.max(previousReleaseId, service.releaseId)
```
Comment (CameronDiver) [inline src/application-manager.coffee]: I don't think that this logic is fully correct, with release pinning.

File: src/application-manager.coffee [hunk 61]
```diff
@@ -0,0 +1,1047 @@
...
+
+		# Returns true if a service matches its target except it should be running and it is not, but we've
+		# already started it before. In this case it means it just exited so we don't want to start it again.
+		alreadyStarted = (serviceId) =>
+			currentServicesPerId[serviceId].isEqualExceptForRunningState(targetServicesPerId[serviceId]) and
+				targetServicesPerId[serviceId].running  and
+				@_containerStarted[currentServicesPerId[serviceId].containerId]
+
+		needUpdate = _.filter toBeMaybeUpdated, (serviceId) ->
+			return !currentServicesPerId[serviceId].isEqual(targetServicesPerId[serviceId]) and !alreadyStarted(serviceId)
```
Comment (CameronDiver) [inline src/application-manager.coffee]: NIT: Unnecessary return (normally I wouldn't say anything but this line is pretty long as it is).

File: src/compose/images.coffee [hunk 62]
```diff
@@ -0,0 +1,301 @@
...
+						Promise.map image.RepoTags, (repoTag) =>
+							@docker.getRegistryAndName(repoTag)
+							.then ({ imageName, tagName }) ->
+								if imageName == supervisorImageInfo.imageName and tagName != supervisorImageInfo.tagName
+									images.push(image.Id)
+		)
+		.then =>
+			toCleanup = _.filter _.uniq(images), (image) =>
+				!@imageCleanupFailures[image]? or Date.now() - @imageCleanupFailures[image] > constants.imageCleanupErrorIgnoreTimeout
+			#console.log(toCleanup)
```
Comment (CameronDiver) [inline src/compose/images.coffee]: Debugging.

File: src/compose/service.coffee [hunk 63]
```diff
@@ -0,0 +1,732 @@
...
+				volumes.push(vol)
+		volumes = volumes.concat(@defaultBinds())
+		volumes = _.union(_.keys(imageInfo?.Config?.Volumes), volumes)
+		@volumes = volumes
+		return @volumes
+
+	getNamedVolumes: =>
+		defaults = @defaultBinds()
+		validVolumes = _.map @volumes, (vol) ->
+			if _.includes(defaults, vol) or !/:/.test(vol)
```
Comment (CameronDiver) [inline src/compose/service.coffee]: It might be worth using `vol.includes(':')` rather than using the the regex engine.

File: src/compose/service.coffee [hunk 64]
```diff
@@ -0,0 +1,732 @@
...
+		if @expose?
+			for port in @expose
+				exposedPorts[port + '/tcp'] = {}
+		return { exposedPorts, portBindings }
+
+	getBindsAndVolumes: =>
+		binds = []
+		volumes = {}
+		for vol in @volumes
+			isBind = /:/.test(vol)
```
Comment (CameronDiver) [inline src/compose/service.coffee]: And here.

File: src/compose/networks.coffee [hunk 65]
```diff
@@ -0,0 +1,95 @@
...
+		@docker.getNetwork(constants.supervisorNetworkInterface).inspect()
+		.then (net) ->
+			if net.Options['com.docker.network.bridge.name'] != constants.supervisorNetworkInterface
+				removeIt()
+			else
+				fs.statAsync("/sys/class/net/#{constants.supervisorNetworkInterface}")
+				.catch ENOENT, ->
+					removeIt()
+		.catch NotFoundError, =>
+			console.log('Creating supervisor0 network')
```
Comment (zvin) [inline src/compose/networks.coffee]: console.log

File: src/compose/service-manager.coffee [hunk 66]
```diff
@@ -0,0 +1,278 @@
...
+						return containerObj.remove(v: true)
+					return
+				# 404 means the container doesn't exist, precisely what we want! :D
+				if statusCode is 404
+					@logger.logSystemEvent(logTypes.stopRemoveServiceNoop, { service })
+					return
+				throw err
+			.tap =>
+				delete @containerHasDied[containerId]
+			.tap =>
```
Comment (zvin) [inline src/compose/service-manager.coffee]: this `tap` is not needed

File: src/compose/service-manager.coffee [hunk 67]
```diff
@@ -0,0 +1,278 @@
...
+				return @docker.getContainer(existingService.containerId)
+			conf = service.toContainerConfig()
+			nets = service.extraNetworksToJoin()
+			@logger.logSystemEvent(logTypes.installService, { service })
+			@reportNewStatus(mockContainerId, service, 'Installing')
+			@docker.createContainer(conf)
+			.tap (container) =>
+				service.containerId = container.id
+				Promise.map nets, ({ name, endpointConfig }) =>
+					console.log('Connecting ' + container.id + ' to network ' + name)
```
Comment (zvin) [inline src/compose/service-manager.coffee]: console.log

File: src/compose/service-manager.coffee [hunk 68]
```diff
@@ -0,0 +1,278 @@
...
+					@docker.getNetwork(name).connect({ Container: container.id, EndpointConfig: endpointConfig })
+			.tap =>
+				@logger.logSystemEvent(logTypes.installServiceSuccess, { service })
+		.catch (err) =>
```
Comment (zvin) [inline src/compose/service-manager.coffee]: `tapCatch`

File: src/compose/service-manager.coffee [hunk 69]
```diff
@@ -0,0 +1,278 @@
...
+
+				if statusCode is 500 and err.message?.trim?()?.match(/exec format error$/)
+					# Provide a friendlier error message for "exec format error"
+					@config.get('deviceType')
+					.then (deviceType) ->
+						throw new Error("Application architecture incompatible with #{deviceType}: exec format error")
+				else
+					# rethrow the same error
+					throw err
+			.catch (err) =>
```
Comment (zvin) [inline src/compose/service-manager.coffee]: `tapCatch`

File: src/compose/service-manager.coffee [hunk 70]
```diff
@@ -0,0 +1,278 @@
...
+								delete @containerHasDied[data.id]
+								@logger.logSystemEvent(logTypes.serviceRestart, { service })
+								@logger.attach(@docker, data.id, service.serviceId)
+					.catch (err) ->
+						console.error('Error on docker event:', err, err.stack)
+					return
+			new Promise (resolve, reject) ->
+				parser
+				.on 'error', (err) ->
+					console.error('Error on docker events stream', err)
```
Comment (zvin) [inline src/compose/service-manager.coffee]: console.error

File: src/compose/volumes.coffee [hunk 71]
```diff
@@ -0,0 +1,105 @@
...
+		.then (vol) =>
+			if !@isEqualConfig(vol.config, config)
+				throw new Error("Trying to create volume '#{name}', but a volume with same name and different configuration exists")
+		.catch NotFoundError, =>
+			@docker.createVolume({
+				Name: "#{appId}_#{name}"
+				Labels: labels
+				DriverOpts: driverOpts
+			})
+		.catch (err) =>
```
Comment (zvin) [inline src/compose/volumes.coffee]: `tapCatch`

File: src/compose/volumes.coffee [hunk 72]
```diff
@@ -0,0 +1,105 @@
...
+		name = defaultLegacyVolume()
+		@create({ name, appId })
+		.then (v) ->
+			v.inspect()
+		.then (v) ->
+			volumePath = path.join(constants.rootMountPoint, v.Mountpoint)
+			legacyPath = path.join(constants.rootMountPoint, constants.dataPath, appId.toString())
+			fs.renameAsync(legacyPath, volumePath)
+			.then ->
+				fs.openAsync(path.dirname(volumePath))
```
Comment (zvin) [inline src/compose/volumes.coffee]: Does this mean that if we don't open, sync and close a file's parent folder after renaming it we'll get into issues?

Comment (zvin) [reply src/compose/volumes.coffee]: If yes, it might be worth putting that logic in a `safeRename` function.

File: src/config.coffee [hunk 73]
```diff
@@ -1,41 +1,349 @@
...
+		@readLockConfigJson = =>
+			@_readLock('config.json')
+			.disposer (release) ->
+				release()
+
+	writeConfigJson: =>
+		atomicWritePossible = true
+		@configJsonPathOnHost()
+		.catch (err) =>
+			console.error(err.message)
```
Comment (zvin) [inline src/config.coffee]: console.error

File: src/config.coffee [hunk 74]
```diff
@@ -1,41 +1,349 @@
...
+						delete @configJsonCache[key]
+					changed = true
+			.then =>
+				if changed
+					@writeConfigJson()
+
+	configJsonRemove: (key) =>
+		changed = false
+		Promise.using @writeLockConfigJson(), =>
+			Promise.try =>
```
Comment (zvin) [inline src/config.coffee]: useless Promise.try and then

File: src/config.coffee [hunk 75]
```diff
@@ -1,41 +1,349 @@
...
+					# In non-resinOS hosts (or older than 1.0.0), if CONFIG_JSON_PATH wasn't passed then we can't do atomic changes
+					# (only access to config.json we have is in /boot, which is assumed to be a file bind mount where rename is impossible)
+					throw new Error('Could not determine config.json path on host, atomic write will not be possible')
+		.then (path) =>
+			return "#{@constants.rootMountPoint}#{path}"
+
+	configJsonPath: =>
+		@configJsonPathOnHost()
+		.catch (err) =>
+			console.error(err.message)
```
Comment (zvin) [inline src/config.coffee]: console.error

File: src/config.coffee [hunk 76]
```diff
@@ -1,41 +1,349 @@
...
+			return @constants.configJsonNonAtomicPath
+
+	readConfigJson: =>
+		@configJsonPath()
+		.then (path) ->
+			fs.readFileAsync(path)
+			.then(JSON.parse)
```
Comment (zvin) [inline src/config.coffee]: NIT: this then could be less indented

File: src/device-config.coffee [hunk 77]
```diff
@@ -1,15 +1,316 @@
...
+				.catch (err) =>
+					@logger.logConfigChange(step.humanReadableTarget, { err })
+					throw err
+			setLogToDisplay: (step) =>
+				logValue = { RESIN_HOST_LOG_TO_DISPLAY: step.target }
+				@logger.logConfigChange(logValue)
+				@setLogToDisplay(step.target)
+				.then =>
+					@logger.logConfigChange(logValue, { success: true })
+				.catch (err) =>
```
Comment (zvin) [inline src/device-config.coffee]: `tapCatch`

File: src/device-config.coffee [hunk 78]
```diff
@@ -1,15 +1,316 @@
...
+			lockOverride: { envVarName: 'RESIN_SUPERVISOR_OVERRIDE_LOCK', varType: 'bool', defaultValue: 'false' }
+		}
+		@validKeys = [ 'RESIN_HOST_LOG_TO_DISPLAY', 'RESIN_SUPERVISOR_VPN_CONTROL', 'RESIN_OVERRIDE_LOCK' ].concat(_.map(@configKeys, 'envVarName'))
+		@actionExecutors = {
+			changeConfig: (step) =>
+				@logger.logConfigChange(step.humanReadableTarget)
+				@config.set(step.target)
+				.then =>
+					@logger.logConfigChange(step.humanReadableTarget, { success: true })
+				.catch (err) =>
```
Comment (zvin) [inline src/device-config.coffee]: `tapCatch`

File: src/device-config.coffee [hunk 79]
```diff
@@ -1,15 +1,316 @@
...
+					throw err
+			setVPNEnabled: (step, { initial = false } = {}) =>
+				logValue = { RESIN_SUPERVISOR_VPN_CONTROL: step.target }
+				if !initial
+					@logger.logConfigChange(logValue)
+				@setVPNEnabled(step.target)
+				.then =>
+					if !initial
+						@logger.logConfigChange(logValue, { success: true })
+				.catch (err) =>
```
Comment (zvin) [inline src/device-config.coffee]: `tapCatch`

File: src/device-config.coffee [hunk 80]
```diff
@@ -1,15 +1,316 @@
...
+
+			# Here's the dangerous part:
+			childProcess.execAsync("mount -t vfat -o remount,rw #{bootBlockDevice} #{bootMountPoint}")
+			.then ->
+				fsUtils.writeFileAtomic(bootConfigPath, configStatements.join('\n') + '\n')
+			.then =>
+				@logger.logSystemMessage("Applied boot config: #{JSON.stringify(conf)}", {}, 'Apply boot config success')
+				@rebootRequired = true
+				return true
+		.catch (err) =>
```
Comment (zvin) [inline src/device-config.coffee]: `tapCatch`

File: src/device-config.coffee [hunk 81]
```diff
@@ -1,15 +1,316 @@
...
+			throw err
+
+	getVPNEnabled: ->
+		gosuper.get('/v1/vpncontrol', { json: true })
+		.spread (res, body) ->
+			if res.statusCode != 200
+				throw new Error("Error getting vpn status: #{res.statusCode} #{body.Error}")
+			@gosuperHealthy = true
+			return Boolean(body.Data)
+		.catch (err) =>
```
Comment (zvin) [inline src/device-config.coffee]: `tapCatch`

File: src/device-state.coffee [hunk 82]
```diff
@@ -0,0 +1,512 @@
...
+					when 'noop'
+						Promise.resolve()
+					else
+						throw new Error("Invalid action #{step.action}")
+
+	applyStep: (step, { force, initial, intermediate, skipLock }) =>
+		if @shuttingDown
+			return
+		@executeStepAction(step, { force, initial, skipLock })
+		.catch (err) =>
```
Comment (zvin) [inline src/device-state.coffee]: `tapCatch`

File: src/device-state.coffee [hunk 83]
```diff
@@ -0,0 +1,512 @@
...
+					@lastSuccessfulUpdate = Date.now()
+					@reportCurrentState(update_failed: false, update_pending: false, update_downloaded: false)
+				return
+			if !intermediate
+				@reportCurrentState(update_pending: true)
+			if _.every(steps, (step) -> step.action == 'noop')
+				nextDelay = 1000
+			Promise.map steps, (step) =>
+				@applyStep(step, { force, initial, intermediate, skipLock })
+			.then ->
```
Comment (zvin) [inline src/device-state.coffee]:
```coffeescript
.then ->
    Promise.delay(nextDelay)
.then ->
```
could be 
```coffeescript
.delay(nextDelay)
.then ->
```

File: src/lib/device.coffee [hunk 84]
```diff
@@ -0,0 +1,15 @@
...
+		if res.statusCode != 202
+			throw new Error(body.Error)
+		return body
+
+exports.shutdown = ->
+	gosuper.post('/v1/shutdown', { json: true })
+	.spread (res, body) ->
+		if res.statusCode != 202
+			throw new Error(body.Error)
+		return body
```
Comment (zvin) [inline src/lib/device.coffee]: this could be factorized

File: src/lib/docker-utils.coffee [hunk 85]
```diff
@@ -0,0 +1,132 @@
...
+				.on('id', (id) -> resolve('sha256:' + id))
+				.on('error', req.abort.bind(req))
+
+module.exports = class DockerUtils extends DockerToolbelt
+	constructor: (opts) ->
+		super(opts)
+		@dockerProgress = new DockerProgress(dockerToolbelt: this)
+		@supervisorTagPromise = @normaliseImageName(constants.supervisorImage)
+		@InvalidNetGatewayError = class InvalidNetGatewayError extends TypedError
+		return this
```
Comment (zvin) [inline src/lib/docker-utils.coffee]: Is this `return this` needed?

File: src/network.coffee [hunk 86]
```diff
@@ -0,0 +1,110 @@
...
+# Call back for inotify triggered when the VPN status is changed.
+vpnStatusInotifyCallback = ->
+	fs.lstatAsync(constants.vpnStatusPath + '/active')
+	.then ->
+		pauseConnectivityCheck = true
+	.catch ->
+		pauseConnectivityCheck = false
+
+# Use the following to catch EEXIST errors
+EEXIST = (err) -> err.code is 'EEXIST'
```
Comment (zvin) [inline src/network.coffee]: this could be moved to errors.coffee

File: src/proxyvisor.coffee [hunk 87]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
-
-router.get '/v1/dependent-apps', (req, res) ->
-	knex('dependentApp').select()
-	.map (app) ->
-		return {
-			id: parseInt(app.appId)
-			commit: app.commit
+			.catch (err) ->
+				console.error("Error on #{req.method} #{url.parse(req.url).pathname}", err, err.stack)
+				res.status(503).send(err?.message or err or 'Unknown error')
```
Comment (zvin) [inline src/proxyvisor.coffee]: This should probably be a middleware

File: src/compose/images.coffee [hunk 88]
```diff
@@ -0,0 +1,301 @@
...
+				.then =>
+					@logger.logSystemEvent(logTypes.downloadImageSuccess, { image })
+					return true
+				.catch (err) =>
+					@logger.logSystemEvent(logTypes.downloadImageError, { image, error: err })
+					return false
+				.then (success) =>
+					@reportChange(image.imageId)
+					onFinish(success)
+					return
```
Comment (zvin) [inline src/compose/images.coffee]: useless return

File: src/compose/volumes.coffee [hunk 89]
```diff
@@ -0,0 +1,105 @@
...
+			}
+		}
+
+	getAll: =>
+		@docker.listVolumes(filters: label: [ 'io.resin.supervised' ])
+		.then (response) =>
+			volumes = response.Volumes ? []
+			Promise.map volumes, (volume) =>
+				@docker.getVolume(volume.Name).inspect()
+				.then (vol) =>
```
Comment (Page-) [inline src/compose/volumes.coffee]: This can be `.then(@format)`

File: src/compose/volumes.coffee [hunk 90]
```diff
@@ -0,0 +1,105 @@
...
+					@format(vol)
+
+	getAllByAppId: (appId) =>
+		@getAll()
+		.then (volumes) ->
+			_.filter(volumes, (v) -> v.appId == appId)
```
Comment (Page-) [inline src/compose/volumes.coffee]: This can be
```coffee
_.filter(volumes, { appId })

File: src/compose/volumes.coffee [hunk 91]
```diff
@@ -0,0 +1,105 @@
...
+
+	get: ({ name, appId }) ->
+		@docker.getVolume("#{appId}_#{name}").inspect()
+		.then (volume) =>
```
Comment (Page-) [inline src/compose/volumes.coffee]: This can be `.then(@format)`

File: src/compose/volumes.coffee [hunk 92]
```diff
@@ -0,0 +1,105 @@
...
+				DriverOpts: driverOpts
+			})
+		.catch (err) =>
+			@logger.logSystemEvent(logTypes.createVolumeError, { volume: { name }, error: err })
+			throw err
+
+	createFromLegacy: (appId) =>
+		name = defaultLegacyVolume()
+		@create({ name, appId })
+		.then (v) ->
```
Comment (Page-) [inline src/compose/volumes.coffee]: This can be `.call('inspect')`

File: src/compose/volumes.coffee [hunk 93]
```diff
@@ -0,0 +1,105 @@
...
+			v.inspect()
+		.then (v) ->
+			volumePath = path.join(constants.rootMountPoint, v.Mountpoint)
+			legacyPath = path.join(constants.rootMountPoint, constants.dataPath, appId.toString())
+			fs.renameAsync(legacyPath, volumePath)
+			.then ->
+				fs.openAsync(path.dirname(volumePath))
+			.then (parent) ->
```
Comment (Page-) [inline src/compose/volumes.coffee]: I think this can be
```coffee
.tap(fs.fsyncAsync)
.then(fs.closeAsync)

File: src/config.coffee [hunk 94]
```diff
@@ -1,41 +1,349 @@
...
+{ writeAndSyncFile, writeFileAtomic } = require './lib/fs-utils'
+osRelease = require './lib/os-release'
+supervisorVersion = require './lib/supervisor-version'
+constants = require './lib/constants'
+
+module.exports = class Config extends EventEmitter
+	constructor: ({ @db, @configPath }) ->
+		# These are values that come from env vars or hardcoded defaults and can be resolved synchronously
+		# Defaults needed for both gosuper and node supervisor are declared in entry.sh
+		@constants = constants
```
Comment (Page-) [inline src/config.coffee]: Why do we assign `constants` to the class instance? Any reason we don't just use the original each time?

File: src/config.coffee [hunk 95]
```diff
@@ -1,41 +1,349 @@
...
+						subscribe_key: pubnubSubscribeKey
+						publish_key: pubnubPublishKey
+						ssl: true
+					}
+					return pubnub
+			resinApiEndpoint: =>
+				# Fall back to checking if an API endpoint was passed via env vars if there's none in config.json (legacy)
+				@get('apiEndpoint')
+				.then (apiEndpoint) ->
+					return apiEndpoint ? @constants.apiEndpointFromEnv
```
Comment (Page-) [inline src/config.coffee]: REQUIRED CHANGE

```
@constants.apiEndpointFromEnv
```
will fail because you used a thin arrow - I think it should just be `constants.apiEndpointFromEnv` though in order to avoid this source of confusion

File: src/config.coffee [hunk 96]
```diff
@@ -1,41 +1,349 @@
...
+			lockOverride: { source: 'db', mutable: true, default: 'false' }
+			legacyAppsPresent: { source: 'db', mutable: true, default: 'false' }
+		}
+
+		@configJsonCache = {}
+
+		@_lock = new Lock()
+		@_writeLock = Promise.promisify(@_lock.async.writeLock)
+		@writeLockConfigJson = =>
+			@_writeLock('config.json')
```
Comment (Page-) [inline src/config.coffee]: If you change this to just 
```coffeee
_writeLock('config.json')
```
then you avoid any risk of exposing it (I assume the `_` is to denote it's meant to be private) and can lose the fat arrow  as well

File: src/config.coffee [hunk 97]
```diff
@@ -1,41 +1,349 @@
...
+			.disposer (release) ->
+				release()
+
+		@_readLock = Promise.promisify(@_lock.async.readLock)
+		@readLockConfigJson = =>
+			@_readLock('config.json')
```
Comment (Page-) [inline src/config.coffee]: Same here

File: src/config.coffee [hunk 98]
```diff
@@ -1,41 +1,349 @@
...
+					.then ([ conf ]) ->
+						return conf?.value
+		.then (value) =>
+			if !value? and @schema[key]?.default?
+				return @schema[key].default
+			return value
+
+	getMany: (keys, trx) =>
+		# Get the values for several keys in an array
+		Promise.all(_.map(keys, (key) => @get(key, trx) ))
```
Comment (Page-) [inline src/config.coffee]: Can this be a `Promise.map`?

File: src/device-config.coffee [hunk 99]
```diff
@@ -1,15 +1,316 @@
...
+		targetBootConfig = @envToBootConfig(target)
+		currentBootConfig = @envToBootConfig(current)
+		if !_.isEqual(currentBootConfig, targetBootConfig)
+			for key in forbiddenConfigKeys
+				if currentBootConfig[key] != targetBootConfig[key]
+					err = "Attempt to change blacklisted config value #{key}"
+					@logger.logSystemMessage(err, { error: err }, 'Apply boot config error')
+					throw new Error(err)
+			return true
+		else return false
```
Comment (Page-) [inline src/device-config.coffee]: There's no need for the `else`

File: src/device-config.coffee [hunk 100]
```diff
@@ -1,15 +1,316 @@
...
+					target
+				})
+			if !_.isEmpty(steps)
+				return
+			if @rebootRequired
+				steps.push({
+					action: 'reboot'
+				})
+			return
+		.then ->
```
Comment (Page-) [inline src/device-config.coffee]: This can be `.return(steps)`

File: src/device-config.coffee [hunk 101]
```diff
@@ -1,15 +1,316 @@
...
+						keyValue = /^(initramfs) (.+)/.exec(configStr)
+						if keyValue?
+							conf[keyValue[1]] = keyValue[2]
+				return @bootConfigToEnv(conf)
+
+	getLogToDisplay: ->
+		gosuper.get('/v1/log-to-display', { json: true })
+		.spread (res, body) ->
+			if res.statusCode == 404
+				return undefined
```
Comment (Page-) [inline src/device-config.coffee]: There's no need for the `undefined`

File: src/device-state.coffee [hunk 102]
```diff
@@ -0,0 +1,512 @@
+Promise = require 'bluebird'
```
Comment (Page-) [inline src/device-state.coffee]: Reviewed up here

**Comment by Page-** [comment]
Oh, it's request changes because there are some things that look like they would cause real issues, I've marked them with `REQUIRED CHANGES` at the top

File: src/api-binder.coffee [hunk 103]
```diff
@@ -0,0 +1,395 @@
...
+		.then =>
+			# If we have an existing device key we first check if it's valid, because if it is we can just use that
+			if opts.deviceApiKey?
+				@fetchDevice(opts.uuid, opts.deviceApiKey, opts.apiTimeout)
+		.then (device) =>
+			if device?
+				return device
+			# If it's not valid/doesn't exist then we try to use the user/provisioning api key for the exchange
+			@fetchDevice(opts.uuid, opts.provisioningApiKey, opts.apiTimeout)
+			.then (device) ->
```
[the remark this answers is not in the document]
Comment (zvin) [reply src/api-binder.coffee]: right, please ignore my comment

File: src/compose/images.coffee [hunk 104]
```diff
@@ -0,0 +1,301 @@
...
+			image = _.clone(image)
+			image.name = imageName
+			@markAsSupervised(image)
+			.then =>
+				@inspectByName(imageName)
+				.then (img) =>
+					@db.models('image').update({ dockerImageId: img.Id }).where(image)
+			.then ->
+				onFinish(true)
+				return
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/compose/images.coffee]: Not really, if onFinish happens to return a Promise we don't want to wait on it.

File: src/compose/networks.coffee (hunk 65 above)
Comment (pcarranzav) [reply src/compose/networks.coffee]: Yeah, I want to have this one in the logs just in case - if we see a lot of these in the field we may catch something going weird with docker networking (I've seen the network needs to be recreated sometimes and couldn't figure out why)

File: src/compose/images.coffee (hunk 104 above)
[the remark this answers is not in the document]
Comment (zvin) [reply src/compose/images.coffee]: correct, please ignore

File: src/migrations/20171129013519_legacy.js [hunk 105]
```diff
@@ -0,0 +1,136 @@
...
+
+// It's a bit ugly for a migration (it's unusual that migrations check for existence of tables and columns)
+// but being the first migration for a legacy system, this is the easiest way to bring the db
+// to a known schema to start doing proper migrations afterwards.
+// For reference, compare this to db.coffee in old supervisors (e.g. v6.4.2), but consider we've added
+// a few dropColumn and dropTable calls to delete things that were removed throughout the supervisor's
+// history without actually adding drop statements (mostly just becoming unused, but still there).
+
+exports.up = function (knex, Promise) {
+	let addColumn = function (table, column, type) {
```
Comment (Page-) [inline src/migrations/20171129013519_legacy.js]: My guess is that all these `let`s should be `const`s

File: src/migrations/20171129013519_legacy.js [hunk 106]
```diff
@@ -0,0 +1,136 @@
...
+				addColumn('dependentDevice', 'lock_expiry_date', 'dateTime')
+			])
+		}),
+		dropTable('image'),
+		dropTable('container')
+	])
+}
+
+exports.down = function(knex, Promise) {
+	return Promise.try(() => { throw new Error('Not implemented') })
```
Comment (Page-) [inline src/migrations/20171129013519_legacy.js]: This is better as
```
return Promise.reject(new Error('Not implemented'))

File: src/migrations/20171129064057_multicontainer.js [hunk 107]
```diff
@@ -0,0 +1,311 @@
...
+		appId: appId,
+		commit: app.commit,
+		name: app.name,
+		releaseId: 1,
+		networks: {},
+		volumes: {}
+	}
+	let defaultVolume = defaultLegacyVolume(appId)
+	newApp.volumes[defaultVolume] = {}
+	let updateStrategy = conf['RESIN_SUPERVISOR_UPDATE_STRATEGY']
```
Comment (Page-) [inline src/migrations/20171129064057_multicontainer.js]: These can be done as
```js
const updateStrategy = _.get(conf, 'RESIN_SUPERVISOR_UPDATE_STRATEGY', 'download-then-kill')
```
etc

File: src/migrations/20171129064057_multicontainer.js [hunk 108]
```diff
@@ -0,0 +1,311 @@
...
+	}
+	let handoverTimeout = conf['RESIN_SUPERVISOR_HANDOVER_TIMEOUT']
+	if (handoverTimeout == null) {
+		handoverTimeout = ''
+	}
+	let restartPolicy = conf['RESIN_APP_RESTART_POLICY']
+	if (restartPolicy == null) {
+		restartPolicy = 'always'
+	}
+	newApp.services = [
```
Comment (Page-) [inline src/migrations/20171129064057_multicontainer.js]: @dfunckt could you check this composition out, you seemed good at spotting issues with them in the api :P

File: src/migrations/20171129064057_multicontainer.js [hunk 109]
```diff
@@ -0,0 +1,311 @@
...
+								'RESIN_SUPERVISOR_CONNECTIVITY_CHECK': 'connectivityCheckEnabled',
+								'RESIN_SUPERVISOR_LOG_CONTROL': 'loggingEnabled',
+								'RESIN_SUPERVISOR_DELTA': 'delta',
+								'RESIN_SUPERVISOR_DELTA_REQUEST_TIMEOUT': 'deltaRequestTimeout',
+								'RESIN_SUPERVISOR_DELTA_APPLY_TIMEOUT': 'deltaApplyTimeout',
+								'RESIN_SUPERVISOR_DELTA_RETRY_COUNT': 'deltaRetryCount',
+								'RESIN_SUPERVISOR_DELTA_RETRY_INTERVAL': 'deltaRequestTimeout',
+								'RESIN_SUPERVISOR_OVERRIDE_LOCK': 'lockOverride'
+							}
+							for (let envVarName in values) {
```
Comment (Page-) [inline src/migrations/20171129064057_multicontainer.js]: I think this would be nicer as a `Promise.map`

File: src/migrations/20171214172530_image_docker_id.js [hunk 110]
```diff
@@ -0,0 +1,10 @@
+// Adds a dockerImageId column to the image table to identify images downloaded with deltas
+exports.up = function (knex, Promise) {
+	return knex.schema.table('image', (t) => {
+			t.string('dockerImageId')
+		})
+}
+
+exports.down = function(knex, Promise) {
+	return Promise.try(() => { throw new Error('Not implemented') })
```
Comment (Page-) [inline src/migrations/20171214172530_image_docker_id.js]: `Promise.reject`

File: src/migrations/20171214172530_image_docker_id.js [hunk 111]
```diff
@@ -0,0 +1,10 @@
+// Adds a dockerImageId column to the image table to identify images downloaded with deltas
+exports.up = function (knex, Promise) {
+	return knex.schema.table('image', (t) => {
+			t.string('dockerImageId')
```
Comment (Page-) [inline src/migrations/20171214172530_image_docker_id.js]: This is doubly indented

File: src/network.coffee [hunk 112]
```diff
@@ -0,0 +1,110 @@
...
+
+	# Manually trigger the call back to detect cases when VPN was switched on before the supervisor starts.
+	vpnStatusInotifyCallback() if enable
+	customMonitor
+		host: parsedUrl.hostname
+		port: parsedUrl.port ? (if parsedUrl.protocol is 'https:' then 443 else 80)
+		interval: 10 * 1000
+		(connected) ->
+			if onChangeCallback?
+				onChangeCallback(connected)
```
Comment (Page-) [inline src/network.coffee]: This can be 
```
onChangeCallback?(connected)

File: src/network.coffee [hunk 113]
```diff
@@ -0,0 +1,110 @@
...
+	# - docker and balena bridges (docker0, docker1, balena0, etc)
+	# - legacy rce bridges (rce0, etc)
+	# - tun interfaces like the legacy vpn
+	# - the resin VPN interface (resin-vpn)
+	# - loopback interface (lo)
+	# - the bridge for dnsmasq (resin-dns)
+	# - the docker network for the supervisor API (supervisor0)
+	# - custom docker network bridges (br- + 12 hex characters)
+	_.flatten(_.map(_.omitBy(os.networkInterfaces(), (interfaceFields, interfaceName) ->
+		/^(balena[0-9]+)|(docker[0-9]+)|(rce[0-9]+)|(tun[0-9]+)|(resin-vpn)|(lo)|(resin-dns)|(supervisor0)|(br-[0-9a-f]{12})$/.test(interfaceName))
```
Comment (Page-) [inline src/network.coffee]: You should be able to make this
```
/^(?:balena|docker|rce|tun)[0-9]+|tun[0-9]+|resin-vpn|lo|resin-dns|supervisor0|br-[0-9a-f]{12}$/
```

File: src/network.coffee [hunk 114]
```diff
@@ -0,0 +1,110 @@
...
+	, (validInterfaces) ->
+		_.map(_.omitBy(validInterfaces, (a) -> a.family != 'IPv4' ), 'address'))
```
Comment (Page-) [inline src/network.coffee]:
```
_.pickBy(validInterfaces, family: 'IPv4' )

File: src/proxyvisor.coffee [hunk 115]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
 	device.targetEnvironment = JSON.parse(device.targetEnvironment ? '{}')
 	return _.omit(device, 'markedForDeletion', 'logs_channel')
 
+# TODO move to lib/validation
```
Comment (Page-) [inline src/proxyvisor.coffee]: TODO

File: src/proxyvisor.coffee [hunk 116]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
+validStringOrUndefined = (s) ->
+	_.isUndefined(s) or !_.isEmpty(s)
```
Comment (Page-) [inline src/proxyvisor.coffee]: This doesn't check it's a string at all

File: src/proxyvisor.coffee [hunk 117]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
+	if commit?
+		fileToKeep = tarFilename(appId, commit)
+	else
+		fileToKeep = null
+	dir = tarDirectory(appId)
+	fs.readdirAsync(dir)
+	.catchReturn([])
+	.then (files) ->
+		if fileToKeep?
+			files = _.filter files, (file) ->
```
Comment (Page-) [inline src/proxyvisor.coffee]:
```
files = _.reject(files, fileToKeep)

File: src/proxyvisor.coffee [hunk 118]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
+				return file isnt fileToKeep
+		Promise.map files, (file) ->
+			if !fileToKeep? or (file isnt fileToKeep)
```
Comment (Page-) [inline src/proxyvisor.coffee]: This check should be unnecessary because of the `_.filter` above

File: src/proxyvisor.coffee [hunk 119]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
+		if current.dependent?.apps?
+			for app in current.dependent.apps
+				images.push app.image
+		if target.dependent?.apps?
+			for app in target.dependent.apps
+				images.push app.image
+		return images
+
+	_imageAvailable: (image, available) ->
+		_.some(available, (availableImage) -> availableImage.name == image)
```
Comment (Page-) [inline src/proxyvisor.coffee]:
```
_.some(available, name: image)

File: src/proxyvisor.coffee [hunk 120]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
+			targetApps = _.keyBy(target.dependent?.apps ? [], 'appId')
+			targetAppIds = _.keys(targetApps)
+			currentApps = _.keyBy(current.dependent?.apps ? [], 'appId')
+			currentAppIds = _.keys(currentApps)
+			allAppIds = _.union(targetAppIds, currentAppIds)
+
+			for appId in allAppIds
+				devicesForApp = (devices) ->
+					_.filter devices, (d) ->
+						_.includes(_.keys(d.apps), appId)
```
Comment (Page-) [inline src/proxyvisor.coffee]: This should be able to be
```
_.has(d.apps, appId)

File: src/proxyvisor.coffee [hunk 121]
```diff
@@ -32,345 +22,624 @@ parseDeviceFields = (device) ->
...
+			return steps
+
+	getHookEndpoint: (appId) =>
+		@db.models('dependentApp').select('parentApp').where({ appId })
+		.then ([ { parentApp } ]) =>
+			@applications.getTargetApp(parentApp)
+		.then (parentApp) =>
+			Promise.map parentApp?.services ? [], (service) =>
+				@docker.getImageEnv(service.image)
+				.then (imageEnv) ->
```
Comment (Page-) [inline src/proxyvisor.coffee]:
```
.get('RESIN_DEPENDENT_DEVICES_HOOK_ADDRESS')

File: hardcode-migrations.js [hunk 122]
```diff
@@ -0,0 +1,7 @@
+// knex migrations use dynamic requires which break with webpack.
+// This hack makes the migrations directory a constant so that at least we can use webpack contexts for the
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply hardcode-migrations.js]: Knex has a few calls to `require` where the argument is variable: https://github.com/tgriesser/knex/blob/0.12.3/src/migrate/index.js#L317 - these don't get along with webpack because webpack doesn't know where to look for the files to load. If the argument to require is prefixed with a specific path, then webpack can take all of the js files inside that folder and build an object that can be indexed when calling require.
I couldn't find a better way to do this really, and I agree it's fragile (but knex is fixed at "~0.12.3" so we'd have to be careful when upgrading it but we don't risk it breaking accidentally). Happy to hear any other ideas you may have.

File: hardcode-migrations.js [hunk 123]
```diff
@@ -0,0 +1,7 @@
...
+// require.
+module.exports = function (source) {
+  return source.toString().replace("require(directory + '/' + name);", "require('./migrations/' + name);")
+  	.replace("require(_path2.default.join(this._absoluteConfigDir(), name));", "require('./migrations/' + name);")
+}
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply hardcode-migrations.js]: Done

File: src/api-binder.coffee [hunk 124]
```diff
@@ -0,0 +1,395 @@
...
+						envVar = {
+							value
+							device: conf.deviceId
+							name: key
+						}
+						@resinApi.post
+							resource: 'device_config_variable'
+							body: envVar
+							customOptions:
+								apikey: conf.currentApiKey
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/api-binder.coffee]: Done (and switched to using header for auth)

File: src/application-manager.coffee (hunk 60 above)
Comment (pcarranzav) [reply src/application-manager.coffee]: Changed to use the releaseId of the oldest container

File: src/application-manager.coffee [hunk 125]
```diff
@@ -0,0 +1,1047 @@
...
+			{ imageId, force } = req.body
+			{ appId } = req.params
+			@_lockingIfNecessary appId, { force }, =>
+				@applications.getCurrentApp(appId)
+				.then (app) =>
+					if !app?
+						errMsg = "App not found: an app needs to be installed for restart-service to work.
+								If you've recently moved this device from another app,
+								please push an app and wait for it to be installed first."
+						return res.status(404).send(errMsg)
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/application-manager.coffee]: Yes, this is fine for now, as these are legacy endpoints... we can improve error messaging in the future

File: src/application-manager.coffee [hunk 126]
```diff
@@ -0,0 +1,1047 @@
...
+						containerId: service.containerId
+						env: _.omit(service.environment, constants.privateAppEnvVars)
+						releaseId: service.releaseId
+						imageId: service.image
+					}
+					if status.commit?
+						appToSend.commit = status.commit
+					res.json(appToSend)
+			)
+			.catch (err) ->
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/application-manager.coffee]: Nice idea, but I'll leave it for a future PR

File: src/compose/service-manager.coffee (hunk 70 above)
Comment (pcarranzav) [reply src/compose/service-manager.coffee]: Yup, it's on purpose, this should be rare and we'd like to see it in supervisor logs if it happens

File: src/config.coffee (hunk 73 above)
Comment (pcarranzav) [reply src/config.coffee]: On purpose, this is meant to let us know in supervisor  logs if the supervisor is not able to write  to config.json atomically

File: src/proxyvisor.coffee (hunk 87 above)
Comment (pcarranzav) [reply src/proxyvisor.coffee]: Yes, but will address separately

File: src/compose/images.coffee (hunk 88 above)
Comment (pcarranzav) [reply src/compose/images.coffee]: Same as above

File: src/api-binder.coffee [hunk 127]
```diff
@@ -0,0 +1,395 @@
...
+
+DuplicateUuidError = (err) ->
+	_.startsWith(err.message, '"uuid" must be unique')
+
+ExchangeKeyError = class ExchangeKeyError extends TypedError
+
+REPORT_SUCCESS_DELAY = 1000
+REPORT_RETRY_DELAY = 5000
+
+class APIBinderRouter
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/api-binder.coffee]: I'll go with your second suggestion. The first one doesn't work because  of the way express defines the Router object https://github.com/expressjs/express/issues/2413

File: src/api-binder.coffee [hunk 128]
```diff
@@ -0,0 +1,395 @@
...
+		.finally =>
+			@lastTargetStateFetch = process.hrtime()
+
+	_pollTargetState: =>
+		if @_targetStateInterval?
+			clearInterval(@_targetStateInterval)
+			@_targetStateInterval = null
+		@config.get('appUpdatePollInterval')
+		.then (appUpdatePollInterval) =>
+			@_targetStateInterval = setInterval(@getAndSetTargetState, appUpdatePollInterval)
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/api-binder.coffee]: Nice catch! Done

File: src/application-manager.coffee [hunk 129]
```diff
@@ -0,0 +1,1047 @@
...
+				Promise.join(
+					@config.get('fetchOptions')
+					@images.getAvailable()
+					(opts, availableImages) =>
+						opts.deltaSource = @bestDeltaSource(step.image, availableImages)
+						@images.triggerFetch step.image, opts, (success) =>
+							@fetchesInProgress -= 1
+							@timeSpentFetching += process.hrtime(startTime)[0]
+							if success
+								@reportCurrentState(update_downloaded: true)
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/application-manager.coffee]: It's a legacy field for the GET /v1/device endpoint, so it's actually only relevant when there's a single image. I'm adding a comment here to make it clear.

File: src/application-manager.coffee [hunk 130]
```diff
@@ -0,0 +1,1047 @@
...
+
+	setTarget: (apps, dependent , trx) =>
+		setInTransaction = (trx) =>
+			Promise.try =>
+				appsArray = _.map apps, (app, appId) ->
+					appClone = _.clone(app)
+					appClone.appId = checkInt(appId)
+					return appClone
+				Promise.map(appsArray, @normaliseAppForDB)
+				.then (appsForDB) =>
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/application-manager.coffee]: Not really, cause we use `appsForDB` below

File: src/compose/images.coffee [hunk 131]
```diff
@@ -0,0 +1,301 @@
...
+			Promise.try =>
+				if digest?
+					@db.models('image').where('name', 'like', "%@#{digest}").select()
+				else
+					@db.models('image').where(name: imageName).select()
+			.then (imagesFromDB) =>
+				for image in imagesFromDB
+					if image.dockerImageId?
+						return @docker.getImage(image.dockerImageId).inspect()
+				throw err
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/compose/images.coffee]: Not really, this can throw or return an image if it finds it, tapCatch would always throw. Unless I'm misunderstanding how you mean I should use it here.

File: src/compose/service.coffee [hunk 132]
```diff
@@ -0,0 +1,732 @@
...
+			@extendAndSanitiseExposedPorts(opts.imageInfo)
+			{ @exposedPorts, @portBindings } = @getPortsAndPortBindings()
+			@devices = formatDevices(@devices)
+			@addFeaturesFromLabels(opts)
+			if @dns?
+				if !Array.isArray(@dns)
+					@dns = [ @dns ]
+			if @dnsSearch?
+				if !Array.isArray(@dnsSearch)
+					@dnsSearch = [ @dns ]
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/compose/service.coffee]: Done

File: src/config.coffee (hunk 95 above)
Comment (pcarranzav) [reply src/config.coffee]: Done

File: src/event-tracker.coffee [hunk 133]
```diff
@@ -0,0 +1,55 @@
...
+		console.log(arguments...)
+
+	track: (ev, properties = {}) =>
+		# Allow passing in an error directly and having it assigned to the error property.
+		if properties instanceof Error
+			properties = error: properties
+
+		# If the properties has an error argument that is an Error object then it treats it nicely,
+		# rather than letting it become `{}`
+		if properties.error instanceof Error
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/event-tracker.coffee]: I agree, but for now I just want to keep the current behavior https://github.com/resin-io/resin-supervisor/blob/v6.6.3/src/utils.coffee#L41

File: src/event-tracker.coffee [hunk 134]
```diff
@@ -0,0 +1,55 @@
...
+		properties = mask(properties, mixpanelMask)
+		@_logEvent('Event:', ev, JSON.stringify(properties))
+		if !@_client?
+			return
+		# Mutation is bad, and it should feel bad
+		properties = _.assign(properties, @_properties)
+		@_client.track(ev, properties)
+
+	init: ({ offlineMode, mixpanelToken, uuid, mixpanelHost }) ->
+		Promise.try =>
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/event-tracker.coffee]: It doesn't need to be async, but I like the convention of all the init functions called in `supervisor.init` being async - plus I don't want to throw synchronously if for whatever reason mixpanel.init throws.

File: src/lib/docker-utils.coffee [hunk 135]
```diff
@@ -0,0 +1,132 @@
...
+					timeout: requestTimeout
+
+				if b?.token?
+					opts.auth =
+						bearer: b.token
+						sendImmediately: true
+				new Promise (resolve, reject) ->
+					request.get("#{deltaEndpoint}/api/v2/delta?src=#{deltaSource}&dest=#{imgDest}", opts)
+					.on 'response', (res) ->
+						res.resume() # discard response body -- we only care about response headers
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/lib/docker-utils.coffee]: Err not sure if the delta API supports OPTIONS.... but I'd rather keep current behavior from master from now.  @dfunckt would know if we can change this.

File: src/lib/update-lock.coffee [hunk 136]
```diff
@@ -0,0 +1,63 @@
...
+
+exports.lock = do ->
+	_lock = new Lock()
+	_writeLock = Promise.promisify(_lock.async.writeLock)
+	return (appId, { force = false } = {}, fn) ->
+		takeTheLock = ->
+			Promise.try ->
+				return if !appId?
+				dispose = (release) ->
+					Promise.map _.clone(locksTaken), (lockName) ->
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/lib/update-lock.coffee]: Cause I'm mutating locksTaken below with _.pull, which causes a race condition if I don't clone.

File: src/lib/validation.coffee [hunk 137]
```diff
@@ -12,13 +14,66 @@ exports.checkInt = (s, options = {}) ->
...
+	return false if !_.isObject(apps)
+	return false if !_.every apps, (val, appId) ->
+		return false if !isValidShortText(appId) or !checkInt(appId)?
+		return false if !isValidShortText(val.name)
+		return false if val.commit? and (!isValidShortText(val.image) or !isValidShortText(val.commit))
+		return undefinedOrValidEnv(val.config) and undefinedOrValidEnv(val.environment)
+	return true
+
+isValidService = (service, serviceId) ->
+	return false if !isValidEnv(service.environment)
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/lib/validation.coffee]: Nice! I didn't know `_.conformsTo`, looks really handy.

File: src/migrations/20171129064057_multicontainer.js (hunk 107 above)
Comment (pcarranzav) [reply src/migrations/20171129064057_multicontainer.js]: We don't have lodash here (or any other library, for that matter)

File: src/migrations/20171129064057_multicontainer.js [hunk 138]
```diff
@@ -0,0 +1,311 @@
+
+var defaultLegacyVolume = function (appId) {
+	return `resin-app-${appId}`
```
Comment (dfunckt) [inline src/migrations/20171129064057_multicontainer.js]: This shouldn’t matter since I understand you’ll be always loading the value from the local db, but the cli and builder name the volume for legacy apps as “resin-data”. IMO maintaining consistency is good, but up to you.

File: src/migrations/20171129064057_multicontainer.js [hunk 139]
```diff
@@ -0,0 +1,311 @@
...
+			],
+			labels: {
+				'io.resin.features.kernel-modules': '1',
+				'io.resin.features.firmware': '1',
+				'io.resin.features.dbus': '1',
+				'io.resin.features.supervisor-api': '1',
+				'io.resin.features.resin-api': '1',
+				'io.resin.update.strategy': updateStrategy,
+				'io.resin.update.handover-timeout': handoverTimeout,
+				'io.resin.legacy-container': '1'
```
Comment (dfunckt) [inline src/migrations/20171129064057_multicontainer.js]: The cli and builder do not set this label when transforming legacy apps to multicontainer, should they?

File: src/lib/docker-utils.coffee (hunk 135 above)
[the remark this answers is not in the document]
Comment (dfunckt) [reply src/lib/docker-utils.coffee]: Yeah, the delta server does not explicitly support options, unless express.js does some magic reusing the GET handler. In any case, resuming the response to discard it is standard practice when you don’t care about it and in this case specifically the body is only a few bytes so there’s not much benefit implementing options.

**Comment by dfunckt** [comment]
@pcarranzav deltas are not switched on by default, right? After the latest fixes I think they could, what do you think?

File: src/migrations/20171129064057_multicontainer.js (hunk 138 above)
Comment (dfunckt) [reply src/migrations/20171129064057_multicontainer.js]: Hmm, in fact I think it matters — won’t the supervisor try to remove and recreate this volume if it’s given a different value on first api checkin?

Comment (pcarranzav) [reply src/migrations/20171129064057_multicontainer.js]: Yeah, good catch, fixed. Does everything else looks like the default composition?

File: src/migrations/20171129064057_multicontainer.js (hunk 139 above)
Comment (pcarranzav) [reply src/migrations/20171129064057_multicontainer.js]: No need, this is just for the supervisor to know it has to ignore the serviceId difference when comparing if nothing else changed (since we didn't have serviceId for old containers)

File: src/migrations/20171129064057_multicontainer.js (hunk 138 above)
Comment (dfunckt) [reply src/migrations/20171129064057_multicontainer.js]: Yep :+1:

File: src/migrations/20171129064057_multicontainer.js (hunk 139 above)
Comment (pcarranzav) [reply src/migrations/20171129064057_multicontainer.js]: And actually I realized it's also not relevant  here. Only on lib/migration.coffee, for legacy preloaded apps.

File: src/lib/docker-utils.coffee [hunk 140]
```diff
@@ -0,0 +1,131 @@
...
+		.on('error', reject)
+		.on 'response', (res) ->
+			if res.statusCode isnt 200
+				reject(new Error("Got #{res.statusCode} when requesting delta from storage."))
+			else if parseInt(res.headers['content-length']) is 0
+				reject(new Error('Invalid delta URL.'))
+			else
+				deltaStream = dockerDelta.applyDelta(imgSrc, timeout: applyTimeout)
+				res.pipe(deltaStream)
+				.on('id', (id) -> resolve('sha256:' + id))
```
Comment (dfunckt) [inline src/lib/docker-utils.coffee]: @pcarranzav I don't think you should be prepending sha here, the ID you get from docker-delta is the image ID, not the content hash, and you refer to the image with `dockerode.getImage(id)` normally.

Comment (pcarranzav) [reply src/lib/docker-utils.coffee]: The image Id *is* a content hash, even if with deltas it doesn’t match the content of the image. We need to do this so that the id is the same as what you get when you do `docker.getImage(id).inspect().get(‘Id’)`

Comment (dfunckt) [reply src/lib/docker-utils.coffee]: Hmm, yes it is indeed a digest, but I thought that doing `docker.getImage('sha256:abcdef')` wouldn't do it, but it seems it works either way.

File: hardcode-migrations.js (hunk 122 above)
[the remark this answers is not in the document]
Comment (Page-) [reply hardcode-migrations.js]: You can use https://webpack.js.org/plugins/context-replacement-plugin/ to restrict the dynamically inferred context, I'm not sure how easy it would be in this case because it seems that the start of the path could be anything, but that would be the more standard way to do it

[the remark this answers is not in the document]
Comment (pcarranzav) [reply hardcode-migrations.js]: We *are* actually using ContextReplacementPlugin. This hack is the only way I found so far to make it work, as it needs a `resourceRegexp` to match the first part of the required path, and the knex code doesn't fit that structure.

[the remark this answers is not in the document]
Comment (pcarranzav) [reply hardcode-migrations.js]: I even tried to make Webpack ignore those requires and leave them as they are, but Webpack insisted on replacing them with "missing dependency" error messages.

File: src/compose/service.coffee [hunk 141]
```diff
@@ -0,0 +1,709 @@
...
+				return null
+		return _.reject(validVolumes, _.isNil)
+
+	lockPath: =>
+		return updateLock.lockPath(@appId)
+
+	killmePath: =>
+		return killmePath(@appId, @serviceName)
+
+	killmeFullPathOnHost: =>
```
Comment (Page-) [inline src/compose/service.coffee]: For reference there's no difference between fat and thin arrows at the class level - they're both assigned to the prototype in the same way, and I see you've used both here so wanted to check you're aware of that

File: src/compose/images.coffee (hunk 104 above)
[the remark this answers is not in the document]
Comment (Page-) [reply src/compose/images.coffee]: In that case it should be `return null`: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

File: src/compose/images.coffee [hunk 142]
```diff
@@ -0,0 +1,301 @@
...
+			delete @volatileState[imageId]
+			@emit('change')
+
+	triggerFetch: (image, opts, onFinish) =>
+		onProgress = (progress) =>
+			# Only report the percentage if we haven't finished fetching
+			if @volatileState[image.imageId]?
+				@reportChange(image.imageId, { downloadProgress: progress.percentage })
+
+		onFinish ?= _.noop
```
Comment (Page-) [inline src/compose/images.coffee]: You could have `onFinish = _.noop` in the function params instead if you want

File: src/compose/images.coffee [hunk 143]
```diff
@@ -0,0 +1,301 @@
...
+			.catch =>
+				@reportChange(image.imageId, _.merge(_.clone(image), { status: 'Downloading', downloadProgress: 0 }))
+				Promise.try =>
+					if validation.checkTruthy(opts.delta) and opts.deltaSource? and opts.deltaSource != 'resin/scratch'
+						@logger.logSystemEvent(logTypes.downloadImageDelta, { image })
+						@inspectByName(opts.deltaSource)
+						.then (srcImage) =>
+							opts.deltaSourceId = srcImage.Id
+							@docker.rsyncImageWithProgress(imageName, opts, onProgress)
+							.tap (id) =>
```
Comment (Page-) [inline src/compose/images.coffee]: This can be unindented

File: src/compose/images.coffee (hunk 88 above)
Comment (Page-) [reply src/compose/images.coffee]: In that case it should be `return null`: http://bluebirdjs.com/docs/warning-explanations.html#warning-a-promise-was-created-in-a-handler-but-was-not-returned-from-it

File: src/logger.coffee [hunk 144]
```diff
@@ -0,0 +1,155 @@
...
+		@publishQueueRemainingBytes = MAX_LOG_BYTE_SIZE
+		@logsOverflow = false
+		_lock = new Lock()
+		@_writeLock = Promise.promisify(_lock.async.writeLock)
+		@attached = {}
+		@offlineMode = false
+		@publishEnabled = false
+
+	init: ({ pubnub, channel, offlineMode, enable }) =>
+		Promise.try =>
```
Comment (Page-) [inline src/logger.coffee]: This would be nicer with `Promise.method`

File: src/proxyvisor.coffee [hunk 145]
```diff
@@ -32,345 +22,615 @@ parseDeviceFields = (device) ->
...
+						cleanupTars(step.appId)
+
+		}
+		@validActions = _.keys(@actionExecutors)
+
+	bindToAPI: (apiBinder) =>
+		@apiBinder = apiBinder
+
+	executeStepAction: (step) =>
+		Promise.try =>
```
Comment (Page-) [inline src/proxyvisor.coffee]: This would be nicer with `Promise.method`

File: src/proxyvisor.coffee [hunk 146]
```diff
@@ -32,345 +22,615 @@ parseDeviceFields = (device) ->
...
+			imageId: app.imageId
+			parentApp: app.parentApp
+			image: image
+			config: JSON.stringify(app.config ? {})
+			environment: JSON.stringify(app.environment ? {})
+		}
+		return Promise.props(dbApp)
+
+	normaliseDependentDeviceTargetForDB: (device, appCommit) ->
+		Promise.try ->
```
Comment (Page-) [inline src/proxyvisor.coffee]: This would be nicer with `Promise.method`

File: src/proxyvisor.coffee [hunk 147]
```diff
@@ -32,345 +22,615 @@ parseDeviceFields = (device) ->
...
+					appId = _.keys(device.apps)[0]
+					@normaliseDependentDeviceTargetForDB(device, dependent.apps[appId]?.commit)
+				.then (devicesForDB) =>
+					Promise.map devicesForDB, (device) =>
+						@db.upsertModel('dependentDeviceTarget', device, { uuid: device.uuid }, trx)
+					.then ->
+						trx('dependentDeviceTarget').whereNotIn('uuid', _.map(devicesForDB, 'uuid')).del()
+
+	normaliseDependentAppFromDB: (app) ->
+		Promise.try ->
```
Comment (Page-) [inline src/proxyvisor.coffee]: This would be nicer with `Promise.method`

File: src/proxyvisor.coffee [hunk 148]
```diff
@@ -32,345 +22,615 @@ parseDeviceFields = (device) ->
...
+				image: app.image
+				imageId: app.imageId
+				config: JSON.parse(app.config)
+				environment: JSON.parse(app.environment)
+				parentApp: app.parentApp
+			}
+			return outApp
+
+	normaliseDependentDeviceTargetFromDB: (device) ->
+		Promise.try ->
```
Comment (Page-) [inline src/proxyvisor.coffee]: This would be nicer with `Promise.method`

File: src/proxyvisor.coffee [hunk 149]
```diff
@@ -32,345 +22,615 @@ parseDeviceFields = (device) ->
...
+				name: device.name
+				apps: _.mapValues JSON.parse(device.apps), (a) ->
+					a.commit ?= null
+					return a
+
+			}
+			return outDevice
+
+	normaliseDependentDeviceFromDB: (device) ->
+		Promise.try ->
```
Comment (Page-) [inline src/proxyvisor.coffee]: This would be nicer with `Promise.method`

File: src/proxyvisor.coffee [hunk 150]
```diff
@@ -32,345 +22,615 @@ parseDeviceFields = (device) ->
...
+		# if we got to this point, the current app is up to date and devices have the
+		# correct targetCommit, targetEnvironment and targetConfig.
+		hookStep = @_getHookStep(currentDevices, appId)
+		if !_.isEmpty(hookStep.devices)
+			return [ hookStep ]
+		return []
+
+	getRequiredSteps: (availableImages, downloading, current, target, stepsInProgress) =>
+		steps = []
+		Promise.try =>
```
Comment (Page-) [inline src/proxyvisor.coffee]: This would be nicer with `Promise.method`

File: src/application-manager.coffee [hunk 151]
```diff
@@ -0,0 +1,995 @@
...
+			return @bestDeltaSource(image, available)
+		proxyvisorImages = @proxyvisor.imagesInUse(current, target)
+		imagesToRemove = _.filter availableAndUnused, (image) =>
+			notUsedForDelta = !_.includes(deltaSources, image.name)
+			notUsedByProxyvisor = !_.some proxyvisorImages, (proxyvisorImage) => @images.isSameImage(image, { name: proxyvisorImage })
+			return notUsedForDelta and notUsedByProxyvisor
+		return { imagesToSave, imagesToRemove }
+
+	_inferNextSteps: (cleanupNeeded, availableImages, downloading, supervisorNetworkReady, current, target, ignoreImages, { localMode, delta }) =>
+		Promise.try =>
```
Comment (Page-) [inline src/application-manager.coffee]: This would be nicer with `Promise.method`

File: src/application-manager.coffee [hunk 152]
```diff
@@ -0,0 +1,995 @@
...
+		@services.getAll()
+		.map (service) =>
+			@_lockingIfNecessary service.appId, { force, skipLock }, =>
+				@services.kill(service, { removeContainer: false, wait: true })
+				.then =>
+					delete @_containerStarted[service.containerId]
+
+	_lockingIfNecessary: (appId, { force = false, skipLock = false } = {}, fn) =>
+		if skipLock
+			return Promise.try(fn)
```
Comment (Page-) [inline src/application-manager.coffee]: This could use `Promise.method` and then `return fn()`, but it's a take it or leave it imo

File: src/compose/images.coffee [hunk 153]
```diff
@@ -0,0 +1,301 @@
...
+		_.some dockerImages, (dockerImage) =>
+			@_matchesTagOrDigest(image, dockerImage) or image.dockerImageId == dockerImage.Id
+
+	# Gets all images that are supervised, in an object containing name, appId, serviceId, serviceName, imageId, dependent.
+	getAvailable: =>
+		@_withImagesFromDockerAndDB (dockerImages, supervisedImages) =>
+			_.filter(supervisedImages, (image) => @_isAvailableInDocker(image, dockerImages))
+
+	getDownloadingImageIds: =>
+		Promise.try =>
```
Comment (Page-) [inline src/compose/images.coffee]: This would be nicer with `Promise.method`

File: src/event-tracker.coffee [hunk 154]
```diff
@@ -0,0 +1,54 @@
...
```
Comment (Page-) [inline src/event-tracker.coffee]: This would be nicer with `Promise.method`

File: src/lib/update-lock.coffee [hunk 155]
```diff
@@ -0,0 +1,61 @@
...
+	for lockName in locksTaken
+		try
+			lockFile.unlockSync(lockName)
+
+exports.lock = do ->
+	_lock = new Lock()
+	_writeLock = Promise.promisify(_lock.async.writeLock)
+	return (appId, { force = false } = {}, fn) ->
+		takeTheLock = ->
+			Promise.try ->
```
Comment (Page-) [inline src/lib/update-lock.coffee]: This would be nicer with `Promise.method`

File: src/lib/docker-utils.coffee [hunk 156]
```diff
@@ -0,0 +1,131 @@
...
+	fetchImageWithProgress: (image, { uuid, currentApiKey }, onProgress) =>
+		@getRegistryAndName(image)
+		.then ({ registry }) =>
+			dockerOptions =
+				authconfig:
+					username: 'd_' + uuid,
+					password: currentApiKey,
+					serveraddress: registry
+			@dockerProgress.pull(image, onProgress, dockerOptions)
+			.then =>
```
Comment (Page-) [inline src/lib/docker-utils.coffee]: This can be unindented

File: src/device-state.coffee [hunk 157]
```diff
@@ -0,0 +1,502 @@
...
+
+	normaliseLegacy: =>
+		# When legacy apps are present, we kill their containers and migrate their /data to a named volume
+		# (everything else is handled by the knex migration)
+		console.log('Killing legacy containers')
+		@applications.services.killAllLegacy()
+		.then =>
+			console.log('Migrating legacy app volumes')
+			@applications.getTargetApps()
+			.map (app) =>
```
Comment (Page-) [inline src/device-state.coffee]: This can be unindented

File: src/device-config.coffee [hunk 158]
```diff
@@ -1,15 +1,317 @@
...
+gosuper = require './lib/gosuper'
+fsUtils = require './lib/fs-utils'
+{ checkTruthy, checkInt } = require './lib/validation'
+
+hostConfigConfigVarPrefix = 'RESIN_HOST_'
+bootConfigEnvVarPrefix = hostConfigConfigVarPrefix + 'CONFIG_'
+bootBlockDevice = '/dev/mmcblk0p1'
+bootMountPoint = constants.rootMountPoint + constants.bootMountPoint
+bootConfigPath = bootMountPoint + '/config.txt'
+configRegex = ->
```
Comment (Page-) [inline src/device-config.coffee]: Any reason this is a function rather than directly assigning the regex?

File: src/device-config.coffee [hunk 159]
```diff
@@ -1,15 +1,317 @@
...
+						RESIN_HOST_LOG_TO_DISPLAY: (logToDisplayStatus ? '').toString()
+						RESIN_SUPERVISOR_VPN_CONTROL: (vpnStatus ? 'true').toString()
+					}
+					for own key, { envVarName } of @configKeys
+						currentConf[envVarName] = (conf[key] ? '').toString()
+					return _.assign(currentConf, bootConfig)
+			)
+
+	getDefaults: =>
+		Promise.try =>
```
Comment (Page-) [inline src/device-config.coffee]: This would be nicer with `Promise.method`

File: src/device-config.coffee [hunk 160]
```diff
@@ -1,15 +1,317 @@
...
+			if _.isArray(val)
+				return JSON.stringify(val).replace(/^\[(.*)\]$/, '$1')
+			else
+				return val
+
+	readBootConfig: ->
+		fs.readFileAsync(bootConfigPath, 'utf8')
+
+	getBootConfig: (deviceType) =>
+		Promise.try =>
```
Comment (Page-) [inline src/device-config.coffee]: This would be nicer with `Promise.method`

File: src/config.coffee [hunk 161]
```diff
@@ -1,41 +1,343 @@
...
+					setValuesInTransaction(tx)
+		.then =>
+			setImmediate =>
+				@emit('change', keyValues)
+
+	# Clear a value from config.json or DB
+	# (will be used to clear the provisioning key)
+	# only mutable fields!
+	remove: (key) =>
+		Promise.try =>
```
Comment (Page-) [inline src/config.coffee]: This would be nicer with `Promise.method`

File: src/compose/volumes.coffee [hunk 162]
```diff
@@ -0,0 +1,95 @@
...
+	getAllByAppId: (appId) =>
+		@getAll()
+		.then (volumes) ->
+			_.filter(volumes, { appId })
+
+	get: ({ name, appId }) ->
+		@docker.getVolume("#{appId}_#{name}").inspect()
+		.then(@format)
+
+	defaultLabels: ->
```
Comment (Page-) [inline src/compose/volumes.coffee]: This seems like it should just be a constant

File: src/compose/service.coffee [hunk 163]
```diff
@@ -0,0 +1,709 @@
...
+		]
+		isEq = _.isEqual(_.pick(this, propertiesToCompare), _.pick(otherService, propertiesToCompare)) and
+			_.isEqual(_.omit(@environment, [ 'RESIN_DEVICE_NAME_AT_INIT' ]), _.omit(otherService.environment, [ 'RESIN_DEVICE_NAME_AT_INIT' ])) and
+			@hasSameNetworks(otherService) and
+			_.every arraysToCompare, (property) =>
+				_.isEmpty(_.xorWith(this[property], otherService[property], _.isEqual))
+
+		# This can be very useful for debugging so I'm leaving it commented for now.
+		# Uncomment to see the services whenever they don't match.
+		#if !isEq
```
Comment (Page-) [inline src/compose/service.coffee]: This should be removed before merging or hidden behind a `DEBUG` flag (which can be set to be compiled out by webpack for release versions)

File: src/compose/service.coffee [hunk 164]
```diff
@@ -0,0 +1,709 @@
...
+			'image'
+			'command'
+			'entrypoint'
+			'networkMode'
+			'privileged'
+			'restartPolicy'
+			'labels'
+			'portBindings'
+			'exposedPorts'
+			#'memLimit'
```
Comment (Page-) [inline src/compose/service.coffee]: Should these be removed?

File: src/compose/service-manager.coffee [hunk 165]
```diff
@@ -0,0 +1,281 @@
...
+			@emit('change')
+		else if containerId? and @volatileState[containerId]?
+			delete @volatileState[containerId]
+			@emit('change')
+
+	reportNewStatus: (containerId, service, status) =>
+		@reportChange(containerId, _.merge({ status }, _.pick(service, [ 'imageId', 'appId', 'releaseId', 'commit' ])))
+
+	_killContainer: (containerId, service = {}, { removeContainer = true, wait = false }) =>
+		Promise.try =>
```
Comment (Page-) [inline src/compose/service-manager.coffee]: This would be nicer with `Promise.method`

File: src/compose/service-manager.coffee [hunk 166]
```diff
@@ -0,0 +1,281 @@
...
+				delete @containerHasDied[containerId]
+				@logger.logSystemEvent(logTypes.stopServiceSuccess, { service })
+			.catch (err) =>
+				@logger.logSystemEvent(logTypes.stopServiceError, { service, error: err })
+			.finally =>
+				if service.imageId?
+					@reportChange(containerId)
+			if wait
+				return killPromise
+			return
```
Comment (Page-) [inline src/compose/service-manager.coffee]: This should be `return null`

File: src/compose/service-manager.coffee [hunk 167]
```diff
@@ -0,0 +1,281 @@
...
+					@config.get('deviceType')
+					.then (deviceType) ->
+						throw new Error("Application architecture incompatible with #{deviceType}: exec format error")
+				else
+					# rethrow the same error
+					throw err
+			.tapCatch (err) =>
+				# If starting the container failed, we remove it so that it doesn't litter
+				container.remove(v: true)
+				.catch(_.noop)
```
Comment (Page-) [inline src/compose/service-manager.coffee]: This would be better as `.catchReturn()`

File: src/compose/service-manager.coffee [hunk 168]
```diff
@@ -0,0 +1,281 @@
...
+				.then =>
+					@logger.logSystemEvent(logTypes.startServiceError, { service, error: err })
+			.then =>
+				@logger.attach(@docker, container.id, service.serviceId)
+		.tap =>
+			if alreadyStarted
+				@logger.logSystemEvent(logTypes.startServiceNoop, { service })
+			else
+				@logger.logSystemEvent(logTypes.startServiceSuccess, { service })
+		.tap (container) ->
```
Comment (Page-) [inline src/compose/service-manager.coffee]: The `(container)` is unused

File: src/compose/networks.coffee [hunk 169]
```diff
@@ -0,0 +1,92 @@
...
+	supervisorNetworkReady: =>
+		# For mysterious reasons sometimes the balena/docker network exists
+		# but the interface does not
+		fs.statAsync("/sys/class/net/#{constants.supervisorNetworkInterface}")
+		.then =>
+			@docker.getNetwork(constants.supervisorNetworkInterface).inspect()
+		.then (net) ->
+			return net.Options['com.docker.network.bridge.name'] == constants.supervisorNetworkInterface
+		.catchReturn(NotFoundError, false)
+		.catchReturn(ENOENT, false)
```
Comment (Page-) [inline src/compose/networks.coffee]: I think this can be
```
.catchReturn(NotFoundError, ENOENT, false)

File: src/migrations/20171129064057_multicontainer.js [hunk 170]
```diff
@@ -0,0 +1,304 @@
...
+		appId: appId,
+		commit: app.commit,
+		name: app.name,
+		releaseId: 1,
+		networks: {},
+		volumes: {}
+	}
+	const defaultVolume = 'resin-data'
+	newApp.volumes[defaultVolume] = {}
+	let updateStrategy = conf['RESIN_SUPERVISOR_UPDATE_STRATEGY']
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/migrations/20171129064057_multicontainer.js]: Oh, you're right! For some reason I had myself convinced I couldn't require stuff here because of how webpack packages the migrations with the hack, but that's nonsense...

File: src/application-manager.coffee [hunk 171]
```diff
@@ -0,0 +1,995 @@
...
+			res.status(200).send('OK')
+		.catch (err) ->
+			res.status(503).send(err?.message or err or 'Unknown error')
+
+	router.use(applications.proxyvisor.router)
+
+	return router
+
+module.exports = class ApplicationManager extends EventEmitter
+	constructor: ({ @logger, @config, @db, @eventTracker, @deviceState }) ->
```
[the remark this answers is not in the document]
Comment (pcarranzav) [reply src/application-manager.coffee]: It's actually used inside the router - think it's cleaner to explicitly pass it to `createApplicationManagerRouter`? Same with eventTracker and deviceState.

File: src/compose/service.coffee (hunk 141 above)
Comment (pcarranzav) [reply src/compose/service.coffee]: Oh but there is definitely a difference:
```
class A
	constructor: ->
		console.log('created an A')
	slimArrowFn: ->
		console.log(this)
	fatArrowFn: =>
		console.log(this)
```
compiles to:
```
// Generated by CoffeeScript 1.12.2
(function() {
  var A,
    bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  A = (function() {
    function A() {
      this.fatArrowFn = bind(this.fatArrowFn, this);
      console.log('created an A');
    }

    A.prototype.slimArrowFn = function() {
      return console.log(this);
    };

    A.prototype.fatArrowFn = function() {
      return console.log(this);
    };

    return A;

  })();

}).call(this);
```

Notice the `this.fatArrowFn = bind(this.fatArrowFn, this);`. So the fat arrow is safer to use in case we call one of these inside a promise chain e.g.
```
a = new A()
Promise.try(a.fatArrowFn).then(a.slimArrowFn)
```
Here the call to `a.slimArrowFn` will *not* print `a`.

Comment (pcarranzav) [reply src/compose/service.coffee]: (I may have used thin arrows in some places where it'd be better to use a fat one though)

File: src/logger.coffee (hunk 144 above)
Comment (pcarranzav) [reply src/logger.coffee]: Promise.method doesn't work well for any of these methods because they wouldn't allow me to use a fat arrow properly.
Here, `this` inside the init function refers to the logger instance, whereas if I did:
```
  init: Promise.method (...) =>
```
Then `this` inside the init function would refer to the Logger *class* because the Promise.method would run in the context of the class definition. From the coffee-script v1 docs:
>  [...] in the context of a class definition, this is the class object itself [...]

File: src/application-manager.coffee (hunk 171 above)
[the remark this answers is not in the document]
Comment (Page-) [reply src/application-manager.coffee]: Ah, yeah I missed that case because I didn't expect to see a destructuring operator on a class instance

File: src/compose/service.coffee (hunk 141 above)
Comment (Page-) [reply src/compose/service.coffee]: Oh ffs, I even compiled it to check and didn't spot that it added it both to the constructor to bind to an instance as well as to the prototype - my bad.

File: src/logger.coffee (hunk 144 above)
Comment (Page-) [reply src/logger.coffee]: I don't think that section of the coffee-script docs is relevant here, and I'm pretty sure you can use a thin arrow unless you use something like
```coffee
logger = new Logger()
{ init } = logger
init()
```
or
```coffee
logger = new Logger()
logger.init.call(null)
```
if you use it as
```coffee
logger = new Logger()
logger.init()
```
then it'll be fine

Comment (pcarranzav) [reply src/logger.coffee]: It would break any time the function is called inside a Promise chain like `Promise.try(logger.init)`.
Example:
```
Promise = require 'bluebird'
class A
        constructor: ->
                console.log('created an A')
                @importantProperty = 'someValue'
        slimArrowFn: ->
                console.log(@importantProperty)
        fatArrowFn: =>
                Promise.try =>
                        console.log(@importantProperty)
        methodFn: Promise.method ->
                console.log(@importantProperty)
        methodFatArrowFn: Promise.method =>
                console.log(@importantProperty)

a = new A()
Promise.try(a.slimArrowFn)
.then(a.fatArrowFn)
.then(a.methodFn)
.then(a.methodFatArrowFn)
```
Output:
```
pablo@pablo-laptop:~/resin/resin-containers/src/resin-supervisor$ coffee test.coffee 
created an A
undefined
someValue
undefined
undefined
```

So only by using a fat arrow do we ensure that we can always access the instance's properties from within the method without having to manually bind the method by doing `Promise.try(a.slimArrowFn.bind(a))` or `Promise.try( -> a.slimArrowFn())`.
So I'd rather keep the way it is to avoid this accidentally happening at some point in the future.

File: src/compose/networks.coffee (hunk 169 above)
Comment (pcarranzav) [reply src/compose/networks.coffee]: Nope, catchReturn only accepts a single predicate to pattern match the error http://bluebirdjs.com/docs/api/catchreturn.html

File: src/logger.coffee (hunk 144 above)
Comment (Page-) [reply src/logger.coffee]: Is that something you actually make use of?

Comment (pcarranzav) [reply src/logger.coffee]: Maybe not for this particular function, but in general we prefer to do `.then(fn)` rather than `.then( -> fn())`, so I'd rather as a rule ensure that my methods work when we do that (otherwise we'll be scratching our heads when something breaks because we did that simple change)

Comment (pcarranzav) [reply src/logger.coffee]: And by extension, I'd rather have all of the instance methods bound to the instance with a fat arrow, unless it's explicitly a method that I want to be able to call on a different object at some point (which is rare)

File: src/compose/networks.coffee (hunk 169 above)
Comment (Page-) [reply src/compose/networks.coffee]: Ah, it's only `.catch` that allows multiple predicates - I knew I'd used multiple in some cases

File: src/logger.coffee (hunk 144 above)
Comment (pcarranzav) [reply src/logger.coffee]: (All the instance methods that use any `@property`, that is)
