### PR TITLE
Properly handle errors when requesting deltas

### LINKED ISSUE #432: Delta download hangs due to an unhandled timeout error
```
May 07 16:30:30 d72bc73 start-resin-supervisor[20115]: [2017-05-07T16:30:30.990Z] Event: Application delta download {"app":{"appId":"130151","commit":"xxxx","imageId":"registry2.resin.io/microbeastglobal/xxxxxxx","env":"{\"RESIN_APP_ID\":\"130151\",\"RESIN_APP_NAME\":\"microBeastGlobal\",\"RESIN_APP_RELEASE\":\"xxxxxxxx\",\"RESIN_DEVICE_UUID\":\"aaaaaaa\",\"RESIN_DEVICE_NAME_AT_INIT\":\"seattleD3\",\"RESIN_DEVICE_TYPE\":\"raspberrypi3\",\"RESIN_HOST_OS_VERSION\":\"Resin OS 2.0.0+rev2\",\"RESIN_SUPERVISOR_ADDRESS\":\"http://127.0.0.1:48484\",\"RESIN_SUPERVISOR_HOST\":\"127.0.0.1\",\"RESIN_SUPERVISOR_PORT\":48484,\"RESIN_SUPERVISOR_VERSION\":\"4.1.1\",\"RESIN\":\"1\",\"USER\":\"root\",\"ROTATE\":\"180\"}","config":"{\"RESIN_SUPERVISOR_DELTA\":\"1\"}","name":"microBeastGlobal"}}
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]: [2017-05-07T16:31:01.082Z] Unhandled rejection Error: ETIMEDOUT
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]:     at Timeout._onTimeout (/usr/src/app/node_modules/request/request.js:852:19)
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]:     at tryOnTimeout (timers.js:232:11)
May 07 16:31:01 d72bc73 start-resin-supervisor[20115]:     at Timer.listOnTimeout (timers.js:202:5)
```

Seen on Resin OS 2.0.0+rev2 (prod) and Supervisor 4.1.1.

I'm still investigating where this happens, and why it's unhandled.

### PR DESCRIPTION
**Pull request by pcarranzav**
When requesting a delta, a `Promise.join` promise chain was producing unhandled
errors since it consisted in a separate promise chain from the parent function which,
was created with `new Promise`. This commit fixes this by creating the new Promise only
when it's needed, avoiding the creation of a separate promise chain.

Closes #432
Change-Type: patch
Signed-off-by: Pablo Carranza Velez <pablo@resin.io>

### CODE REVIEW

**Comment by pcarranzav** [comment]
@Page- good point, done

File: src/docker-utils.coffee [hunk 1]
```diff
@@ -69,32 +69,31 @@ do ->
...
+					tokenEndpoint = "#{config.apiEndpoint}/auth/v1/token"
+					authOpts =
+						auth:
+							user: 'd_' + uuid
+							pass: apiKey
+							sendImmediately: true
+					url = "#{tokenEndpoint}?service=#{dstInfo.registry}&scope=repository:#{dstInfo.imageName}:pull&scope=repository:#{srcInfo.imageName}:pull"
+					request.getAsync(url, authOpts)
+					.spread (res, body) ->
+						try
```
Comment (Page-) [inline src/docker-utils.coffee]: Would this be better as
```coffee
.get(1)
.then(JSON.parse)
.catchReturn({})
.then (b) ->
	...
```
?
