### PR TITLE
If a device is already provisioned but the key exchange fails, retry …

### LINKED ISSUE #487: Supervisor does not retry apiKey exchange when fails, and throws exception
It can happen that they apiKey -> deviceApiKey exchange does not succeed e.g. for network issues when the supervisor is starting up, but seems like the supervisor does not retry the exchange, instead errors out with things like:

```
Unhandled rejection t: Couldn't fetch device with provisioning key
    at /usr/src/app/dist/app.js:80:17531
    at r (/usr/src/app/dist/app.js:1:2435)
    at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:294:42283)
    at i._settlePromise (/usr/src/app/dist/app.js:294:43083)
    at i._settlePromise0 (/usr/src/app/dist/app.js:294:43782)
    at i._settlePromises (/usr/src/app/dist/app.js:294:45109)
    at i._fulfill (/usr/src/app/dist/app.js:294:44152)
    at i._resolveCallback (/usr/src/app/dist/app.js:294:41023)
    at i._settlePromiseFromHandler (/usr/src/app/dist/app.js:294:42437)
    at i._settlePromise (/usr/src/app/dist/app.js:294:43083)
    at i._settlePromise0 (/usr/src/app/dist/app.js:294:43782)
    at i._settlePromises (/usr/src/app/dist/app.js:294:45109)
    at i._fulfill (/usr/src/app/dist/app.js:294:44152)
    at i._settlePromise (/usr/src/app/dist/app.js:294:43281)
```

### PR DESCRIPTION
**Pull request by pcarranzav**
…it until it succeeds

Closes  #487 
Change-Type: patch
Signed-off-by: Pablo Carranza Velez <pablo@resin.io>

### CODE REVIEW

File: src/bootstrap.coffee [hunk 1]
```diff
@@ -179,38 +179,51 @@ hasDeviceApiKeySupport = (osVersion) ->
...
+exchangeKeyAndUpdateConfig = ->
+	# Only do a key exchange and delete the provisioning key if we're on a Resin OS version
+	# that supports using the deviceApiKey (2.0.2 and above)
+	# or if we're in a non-Resin OS (which is assumed to be updated enough).
+	# Otherwise VPN and other host services that use an API key will break.
+	#
+	# In other cases, we make the apiKey equal the deviceApiKey instead.
+	osRelease.getOSVersion(config.hostOSVersionPath)
+	.then (osVersion) ->
+		hasSupport = hasDeviceApiKeySupport(osVersion)
```
Comment (lekkas) [inline src/bootstrap.coffee]: Since you're at it, would it make sense to use [resin-semver](https://www.npmjs.com/package/resin-semver) in `hasDeviceApiKeySupport()` to compare the resinOS versions?

Comment (pcarranzav) [reply src/bootstrap.coffee]: @lekkas will do, but in a separate PR
