### PR TITLE
Use getRegistryAndName from docker-toolbelt 1.2.0

### LINKED ISSUE #293: Image name parsing for supervisor images in cleanup is broken
And docker-progress 2.2.0 surfaced the bug causing all update cycles to fail

### PR DESCRIPTION
**Pull request by pcarranzav**
Fixes #293 

Depends on https://github.com/resin-io-modules/docker-toolbelt/pull/2 being merged and published as 1.2.0.

### CODE REVIEW

**Comment by pcarranzav** [comment]
@Page- I also added a normalization to all image tags (otherwise this caused the supervisor to kill itself, but it also makes the cleanup more robust). Still approve?

File: src/docker-utils.coffee [hunk 1]
```diff
@@ -101,27 +101,30 @@ do ->
 		Promise.using readLockImages(), ->
 			dockerProgress.pull(image, onProgress)
 
-	supervisorTag = config.supervisorImage
```
Comment (Page-) [inline src/docker-utils.coffee]: I think it makes sense to keep this but as `supervisorTag = normalizeRepoTag(config.supervisorImage)` to avoid repeating the normalisation work each time (it might also be worth making the normalisation/splitting stuff return synchronously, as it doesn't actually need anything async)

File: src/docker-utils.coffee [hunk 2]
```diff
@@ -101,27 +101,30 @@ do ->
...
-	if !/:/g.test(supervisorTag)
-		# If there is no tag then mark it as latest
-		supervisorTag += ':latest'
+	normalizeRepoTag = (image) ->
```
Comment (Page-) [inline src/docker-utils.coffee]: It probably makes sense to have this in the docker-toolbelt?

Comment (pcarranzav) [inline src/docker-utils.coffee]: It does, but I'd rather have it here for now (`buildRepoTag` is used below in other places) and split it out later, so that we can fix this bug quickly.

File: src/docker-utils.coffee (hunk 1 above)
Comment (pcarranzav) [inline src/docker-utils.coffee]: Kept it as a promise, but made it so that it's only computed once

Comment (pcarranzav) [inline src/docker-utils.coffee]: (The getRegistryAndName can throw, so it does make sense that it's wrapped as a Promise)

Comment (Page-) [inline src/docker-utils.coffee]: Well it definitely needs to be error checked, but having something synchronous wrapped in a promise does mean you have to deal with async stuff when you don't necessarily have to

File: src/docker-utils.coffee (hunk 2 above)
Comment (Page-) [inline src/docker-utils.coffee]: I mean I think it'd make sense for buildRepoTag to be in docker to also be in docker-toolbelt?

Comment (pcarranzav) [inline src/docker-utils.coffee]: Yeah, I'll move that out soon, just couldn't have peace of mind until this bug was fixed
